"""
reporter.py — Report writer. Produces both Markdown and HTML output.

Markdown: human-readable, Git-friendly, good for the repo sample.
HTML:     visual dashboard, self-contained single file.
"""

from datetime import datetime, timezone
from typing import Dict, List


# ── Grade helpers ─────────────────────────────────────────────────────────────

_GRADE_ORDER = {"FAIL": 0, "WARN": 1, "INFO": 2, "PASS": 3}

GRADE_SYMBOL = {
    "PASS": "✅ PASS",
    "WARN": "⚠️ WARN",
    "FAIL": "❌ FAIL",
    "INFO": "ℹ️ INFO",
}

# HTML badge classes
GRADE_CLASS = {
    "PASS": "badge-success",
    "WARN": "badge-warning",
    "FAIL": "badge-danger",
    "INFO": "badge-info",
}


def _worst(grades: List[str]) -> str:
    return min(grades, key=lambda g: _GRADE_ORDER.get(g, 99))


def _sym(grade: str) -> str:
    return GRADE_SYMBOL.get(grade, grade)


def _truncate(s: str, n: int = 80) -> str:
    return s if len(s) <= n else s[:n - 3] + "..."


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# ══════════════════════════════════════════════════════════════════════════════
# MARKDOWN
# ══════════════════════════════════════════════════════════════════════════════

def write_markdown(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    output_path: str,
) -> None:
    sections = [
        _md_header(domains),
        _md_executive_summary(
            domains, email_results, security_results, dns_results,
            registrar_results, dns_sec_results, blacklist_results, rdns_results,
        ),
    ]

    for domain in domains:
        if domain in registrar_results:
            sections.append(_md_registrar(domain, registrar_results[domain]))
        if domain in dns_sec_results:
            sections.append(_md_dns_security(domain, dns_sec_results[domain]))
        if domain in dns_results:
            sections.append(_md_dns(domain, dns_results[domain]))
        if domain in email_results:
            sections.append(_md_email(domain, email_results[domain]))
        if domain in blacklist_results:
            sections.append(_md_blacklist(domain, blacklist_results[domain]))
        if domain in rdns_results:
            sections.append(_md_rdns(domain, rdns_results[domain]))
        if domain in security_results:
            sections.append(_md_security(domain, security_results[domain]))

    sections.append(
        "\n---\n\n"
        "*Generated by [cloudflare-reporting](https://github.com/wblv-dev/cloudflare-reporting). "
        "Read-only — no changes made to any zone.*\n"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sections))

    print(f"  Markdown report → {output_path}")


def _md_header(domains: List[str]) -> str:
    domain_list = ", ".join(f"`{d}`" for d in domains)
    return (
        f"# Cloudflare DNS Audit Report\n\n"
        f"**Generated:** {_ts()}  \n"
        f"**Domains:** {domain_list}  \n"
        f"**Tool:** [cloudflare-reporting](https://github.com/wblv-dev/cloudflare-reporting)\n\n"
        f"> Live DNS validation and Cloudflare API audit. "
        f"Grades reflect published state at time of generation.\n\n---\n"
    )


def _md_executive_summary(
    domains, email_results, security_results, dns_results,
    registrar_results, dns_sec_results, blacklist_results, rdns_results,
) -> str:
    lines = [
        "## Executive summary\n",
        "| Domain | DNS | Email | Zone | Registrar | DNSSEC | CAA | Blacklist | rDNS |",
        "|--------|-----|-------|------|-----------|--------|-----|-----------|------|",
    ]

    for d in domains:
        dns_count = dns_results.get(d, {}).get("total", "?")

        email = email_results.get(d, {})
        email_grade = _worst([
            email.get("spf", {}).get("grade", "INFO"),
            email.get("dmarc", {}).get("grade", "INFO"),
        ])

        sec = security_results.get(d)
        if sec:
            passed, total = sec["score"]
            sec_cell = f"{_sym(_worst([r['grade'] for r in sec['results']]))} ({passed}/{total})"
        else:
            sec_cell = "—"

        reg = registrar_results.get(d, {})
        reg_grade = _worst([
            reg.get("expiry", {}).get("grade", "INFO"),
            reg.get("lock", {}).get("grade", "INFO"),
        ])

        ds = dns_sec_results.get(d, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "?")
        caa_g = ds.get("caa", {}).get("grade", "?")

        bl_g = blacklist_results.get(d, {}).get("grade", "?")
        rdns_g = rdns_results.get(d, {}).get("grade", "?")

        lines.append(
            f"| `{d}` | {dns_count} | {_sym(email_grade)} | {sec_cell} "
            f"| {_sym(reg_grade)} | {_sym(dnssec_g)} | {_sym(caa_g)} "
            f"| {_sym(bl_g)} | {_sym(rdns_g)} |"
        )

    return "\n".join(lines) + "\n\n---\n"


def _md_registrar(domain: str, result: dict) -> str:
    lines = [f"## Registrar — `{domain}`\n"]

    if result.get("registrar"):
        lines.append(f"**Registrar:** {result['registrar']}\n")

    if result.get("nameservers"):
        lines.append(f"**Nameservers:** {', '.join(f'`{ns}`' for ns in result['nameservers'])}\n")

    exp = result.get("expiry", {})
    lines.append(f"**Expiry:** {_sym(exp.get('grade', 'INFO'))} — {exp.get('reason', 'Unknown')}")
    if exp.get("expiry"):
        lines.append(f"  \n**Expiry date:** `{exp['expiry']}`")

    lock = result.get("lock", {})
    lines.append(f"\n**Transfer lock:** {_sym(lock.get('grade', 'INFO'))} — {lock.get('reason', 'Unknown')}")

    return "\n".join(lines) + "\n\n"


def _md_dns_security(domain: str, result: dict) -> str:
    lines = [f"## DNS security — `{domain}`\n"]

    dnssec = result.get("dnssec", {})
    lines.append(f"**DNSSEC:** {_sym(dnssec.get('grade', 'INFO'))} — {dnssec.get('reason', '')}")

    caa = result.get("caa", {})
    lines.append(f"\n**CAA:** {_sym(caa.get('grade', 'INFO'))} — {caa.get('reason', '')}")

    if caa.get("records"):
        lines += ["\n| Flags | Tag | Value |", "|-------|-----|-------|"]
        for r in caa["records"]:
            lines.append(f"| {r.get('flags', '')} | `{r.get('tag', '')}` | `{r.get('value', '')}` |")

    dangling = result.get("dangling", {})
    lines.append(f"\n**Dangling CNAMEs:** {_sym(dangling.get('grade', 'INFO'))} — {dangling.get('reason', '')}")

    if dangling.get("dangling"):
        lines += ["\n| Record | Target |", "|--------|--------|"]
        for d in dangling["dangling"]:
            lines.append(f"| `{d['name']}` | `{d['target']}` |")

    return "\n".join(lines) + "\n\n"


def _md_blacklist(domain: str, result: dict) -> str:
    lines = [
        f"## Blacklist — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    listings = result.get("listings", [])
    if listings:
        lines += ["\n| IP | Blacklist | Reason |", "|-----|-----------|--------|"]
        for l in listings:
            lines.append(f"| `{l.get('ip', '')}` | {l.get('blacklist', '')} | {l.get('reason', '')} |")

    return "\n".join(lines) + "\n\n"


def _md_rdns(domain: str, result: dict) -> str:
    lines = [
        f"## Reverse DNS — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    ptr_results = result.get("results", [])
    if ptr_results:
        lines += ["\n| MX Host | IP | PTR | FCrDNS |", "|---------|-----|-----|--------|"]
        for r in ptr_results:
            fcrdns = "✅" if r.get("fcrdns") else "❌"
            ptr = r.get("ptr") or "—"
            lines.append(
                f"| `{r.get('mx_host', '')}` | `{r.get('ip', '')}` | `{ptr}` | {fcrdns} |"
            )

    return "\n".join(lines) + "\n\n"


def _md_dns(domain: str, summary: dict) -> str:
    lines = [f"## DNS inventory — `{domain}`\n",
             f"**Total:** {summary['total']} records  "
             f"(**{summary['proxied']}** proxied through Cloudflare)\n",
             "**By type:**\n",
             "| Type | Count |", "|------|-------|"]
    for rtype, count in summary["by_type"].items():
        lines.append(f"| `{rtype}` | {count} |")

    lines += ["\n**All records:**\n",
              "| Type | Name | Content | TTL | Proxied |",
              "|------|------|---------|-----|---------|"]
    for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
        proxied = "🟠 Yes" if r["proxied"] else "No"
        lines.append(
            f"| `{r['type']}` | `{r['name']}` "
            f"| `{_truncate(r['content'], 60)}` | {r['ttl']} | {proxied} |"
        )
    return "\n".join(lines) + "\n\n"


def _md_email(domain: str, result: dict) -> str:
    lines = [f"## Email security — `{domain}`\n"]

    if not result["has_mail"]:
        lines.append("**MX:** " + (
            "None — domain does not handle email.\n"
            if not result["mx"]
            else "Null MX (RFC 7505) — domain explicitly declares no mail.\n"
        ))
    else:
        lines += ["**MX records:**\n", "| Priority | Host |", "|----------|------|"]
        for mx in result["mx"]:
            lines.append(f"| {mx['priority']} | `{mx['host']}` |")
        lines.append("")

    spf   = result["spf"]
    dmarc = result["dmarc"]

    lines.append(f"**SPF:** {_sym(spf['grade'])} — {spf['reason']}")
    if spf.get("record"):
        lines.append(f"\n```\n{spf['record']}\n```\n")

    lines.append(f"**DMARC:** {_sym(dmarc['grade'])} — {dmarc['reason']}")
    if dmarc.get("rua"):
        lines.append(f"  \n**Reporting (rua):** `{dmarc['rua']}`")
    if dmarc.get("record"):
        lines.append(f"\n```\n{dmarc['record']}\n```\n")

    if result["dkim"]:
        lines += ["**DKIM selectors found:**\n",
                  "| Selector | Record (truncated) |",
                  "|----------|--------------------|"]
        for dk in result["dkim"]:
            lines.append(f"| `{dk['selector']}` | `{_truncate(dk['record'], 60)}` |")
    else:
        lines.append(
            "**DKIM:** No common selectors found. "
            "Add your provider's selector to `DKIM_SELECTORS` in `email_security.py`.\n"
        )

    return "\n".join(lines) + "\n"


def _md_security(domain: str, result: dict) -> str:
    passed, total = result["score"]
    lines = [f"## Zone security — `{domain}`\n",
             f"**Score:** {passed}/{total} checks passed\n",
             "| Check | Recommended | Actual | Grade | Notes |",
             "|-------|-------------|--------|-------|-------|"]
    for r in result["results"]:
        lines.append(
            f"| {r['label']} | `{r.get('recommended','—')}` "
            f"| `{r.get('actual','—')}` | {_sym(r['grade'])} | {r.get('note','')} |"
        )

    failures = [r for r in result["results"] if r["grade"] in ("FAIL", "WARN")]
    if failures:
        lines.append("\n**Findings:**\n")
        for r in failures:
            if r.get("explanation"):
                lines.append(f"- **{r['label']}** ({_sym(r['grade'])}): {r['explanation']}")

    return "\n".join(lines) + "\n\n"


# ══════════════════════════════════════════════════════════════════════════════
# HTML
# ══════════════════════════════════════════════════════════════════════════════

def write_html(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    output_path: str,
) -> None:
    html = "\n".join([
        _html_head(),
        _html_header(domains),
        _html_summary_cards(
            domains, email_results, security_results, dns_results,
            registrar_results, dns_sec_results, blacklist_results, rdns_results,
        ),
        _html_registrar_table(domains, registrar_results),
        _html_dns_security_table(domains, dns_sec_results),
        _html_security_table(domains, security_results),
        _html_email_table(domains, email_results),
        _html_blacklist_table(domains, blacklist_results),
        _html_rdns_table(domains, rdns_results),
        _html_dns_tables(domains, dns_results),
        _html_footer(),
    ])

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"  HTML report     → {output_path}")


def _badge(grade: str, text: str = None) -> str:
    cls  = GRADE_CLASS.get(grade, "badge-info")
    label = text or grade
    return f'<span class="badge {cls}">{label}</span>'


def _html_head() -> str:
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Cloudflare DNS Audit Report</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
  line-height:1.6;color:#1a1a2e;background:#f0f2f5}
.header{background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);
  color:#fff;padding:40px 20px}
.header-inner{max-width:1200px;margin:0 auto;display:flex;
  justify-content:space-between;align-items:flex-end;flex-wrap:wrap;gap:16px}
.header h1{font-size:1.9em;font-weight:600;margin-bottom:4px}
.header .meta{opacity:.8;font-size:.95em}
.container{max-width:1200px;margin:0 auto;padding:32px 20px}
h2{font-size:1.4em;font-weight:600;color:#0f3460;margin:40px 0 16px;
  padding-bottom:8px;border-bottom:2px solid #e2e8f0}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin:24px 0}
.card{padding:24px;border-radius:10px;color:#fff}
.card h3{font-size:.8em;text-transform:uppercase;letter-spacing:.5px;opacity:.9;margin-bottom:8px}
.card .val{font-size:2.2em;font-weight:700}
.card .sub{font-size:.85em;opacity:.85;margin-top:4px}
.c-navy{background:linear-gradient(135deg,#1a1a2e,#0f3460)}
.c-green{background:linear-gradient(135deg,#065f46,#059669)}
.c-orange{background:linear-gradient(135deg,#92400e,#d97706)}
.c-red{background:linear-gradient(135deg,#7f1d1d,#dc2626)}
.c-blue{background:linear-gradient(135deg,#1e3a8a,#3b82f6)}
.c-purple{background:linear-gradient(135deg,#4c1d95,#7c3aed)}
.c-teal{background:linear-gradient(135deg,#134e4a,#0d9488)}
table{width:100%;border-collapse:collapse;margin:16px 0;border-radius:8px;
  overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.1)}
th{background:#0f3460;color:#fff;padding:12px 16px;text-align:left;
  font-size:.85em;font-weight:600;text-transform:uppercase;letter-spacing:.3px}
td{padding:12px 16px;border-bottom:1px solid #e2e8f0;font-size:.9em;vertical-align:top}
tr:last-child td{border-bottom:none}
tr:hover td{background:#f8fafc}
.badge{display:inline-block;padding:3px 10px;border-radius:12px;
  font-size:.8em;font-weight:600;white-space:nowrap}
.badge-success{background:#d1fae5;color:#065f46}
.badge-warning{background:#fef3c7;color:#92400e}
.badge-danger{background:#fee2e2;color:#991b1b}
.badge-info{background:#dbeafe;color:#1e40af}
.domain-section{margin-bottom:48px}
code{font-family:monospace;background:#f1f5f9;padding:1px 5px;border-radius:3px;font-size:.88em}
.footer{text-align:center;padding:32px;color:#64748b;font-size:.85em;border-top:1px solid #e2e8f0;margin-top:40px}
@media(max-width:640px){.header h1{font-size:1.4em}.cards{grid-template-columns:1fr}}
</style>
</head>
<body>"""


def _html_header(domains: List[str]) -> str:
    domain_list = ", ".join(f"<code>{d}</code>" for d in domains)
    return f"""
<div class="header">
  <div class="header-inner">
    <div>
      <h1>Cloudflare DNS Audit Report</h1>
      <div class="meta">Domains: {domain_list}</div>
    </div>
    <div class="meta" style="text-align:right">Generated: {_ts()}</div>
  </div>
</div>
<div class="container">"""


def _html_summary_cards(
    domains, email_results, security_results, dns_results,
    registrar_results, dns_sec_results, blacklist_results, rdns_results,
) -> str:
    total_dns = sum(dns_results.get(d, {}).get("total", 0) for d in domains)

    email_grades = []
    for d in domains:
        e = email_results.get(d, {})
        email_grades += [e.get("spf", {}).get("grade", "INFO"),
                         e.get("dmarc", {}).get("grade", "INFO")]
    email_fail = sum(1 for g in email_grades if g == "FAIL")
    email_pass = sum(1 for g in email_grades if g == "PASS")

    sec_pass = sec_total = 0
    for d in domains:
        sec = security_results.get(d)
        if sec:
            p, t = sec["score"]
            sec_pass += p
            sec_total += t

    # Collect all new check grades
    all_new_grades = []
    for d in domains:
        reg = registrar_results.get(d, {})
        all_new_grades.append(reg.get("expiry", {}).get("grade", "INFO"))
        all_new_grades.append(reg.get("lock", {}).get("grade", "INFO"))
        ds = dns_sec_results.get(d, {})
        all_new_grades.append(ds.get("dnssec", {}).get("grade", "INFO"))
        all_new_grades.append(ds.get("caa", {}).get("grade", "INFO"))
        all_new_grades.append(ds.get("dangling", {}).get("grade", "INFO"))
        all_new_grades.append(blacklist_results.get(d, {}).get("grade", "INFO"))
        all_new_grades.append(rdns_results.get(d, {}).get("grade", "INFO"))

    new_fail = sum(1 for g in all_new_grades if g == "FAIL")
    new_warn = sum(1 for g in all_new_grades if g == "WARN")
    new_pass = sum(1 for g in all_new_grades if g == "PASS")

    return f"""
<h2>Executive summary</h2>
<div class="cards">
  <div class="card c-navy">
    <h3>Domains audited</h3>
    <div class="val">{len(domains)}</div>
    <div class="sub">{total_dns} total DNS records</div>
  </div>
  <div class="card {'c-green' if email_fail == 0 else 'c-red'}">
    <h3>Email security</h3>
    <div class="val">{email_pass} pass</div>
    <div class="sub">{email_fail} fail</div>
  </div>
  <div class="card {'c-green' if sec_total and sec_pass == sec_total else 'c-orange'}">
    <h3>Zone security</h3>
    <div class="val">{sec_pass}/{sec_total}</div>
    <div class="sub">checks passed</div>
  </div>
  <div class="card {'c-green' if new_fail == 0 else 'c-red'}">
    <h3>Infrastructure</h3>
    <div class="val">{new_pass} pass</div>
    <div class="sub">{new_warn} warn &nbsp;·&nbsp; {new_fail} fail</div>
  </div>
</div>"""


def _html_registrar_table(domains, registrar_results) -> str:
    if not registrar_results:
        return ""

    rows = ""
    for domain in domains:
        result = registrar_results.get(domain)
        if not result:
            continue

        exp = result.get("expiry", {})
        lock = result.get("lock", {})
        ns = ", ".join(result.get("nameservers", [])[:4]) or "—"

        rows += (
            f"<tr><td><code>{domain}</code></td>"
            f"<td>{result.get('registrar', '—')}</td>"
            f"<td>{_badge(exp.get('grade', 'INFO'))} <small>{exp.get('reason', '')}</small></td>"
            f"<td>{_badge(lock.get('grade', 'INFO'))} <small>{'Locked' if lock.get('locked') else 'Unlocked'}</small></td>"
            f"<td><small>{ns}</small></td></tr>\n"
        )

    return f"""
<h2>Registrar &amp; domain status</h2>
<table>
  <thead><tr>
    <th>Domain</th><th>Registrar</th><th>Expiry</th>
    <th>Transfer lock</th><th>Nameservers</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>"""


def _html_dns_security_table(domains, dns_sec_results) -> str:
    if not dns_sec_results:
        return ""

    rows = ""
    for domain in domains:
        result = dns_sec_results.get(domain)
        if not result:
            continue

        dnssec = result.get("dnssec", {})
        caa = result.get("caa", {})
        dangling = result.get("dangling", {})
        dang_count = len(dangling.get("dangling", []))

        rows += (
            f"<tr><td><code>{domain}</code></td>"
            f"<td>{_badge(dnssec.get('grade', 'INFO'))} <small>{dnssec.get('reason', '')}</small></td>"
            f"<td>{_badge(caa.get('grade', 'INFO'))} <small>{caa.get('reason', '')}</small></td>"
            f"<td>{_badge(dangling.get('grade', 'INFO'))} "
            f"<small>{dang_count} dangling</small></td></tr>\n"
        )

    return f"""
<h2>DNS security</h2>
<table>
  <thead><tr>
    <th>Domain</th><th>DNSSEC</th><th>CAA</th><th>Dangling CNAMEs</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>"""


def _html_security_table(domains, security_results) -> str:
    if not security_results:
        return ""

    rows = ""
    for domain in domains:
        sec = security_results.get(domain)
        if not sec:
            continue
        for r in sec["results"]:
            rows += (
                f"<tr><td><code>{domain}</code></td>"
                f"<td>{r['label']}</td>"
                f"<td><code>{r.get('recommended','—')}</code></td>"
                f"<td><code>{r.get('actual','—')}</code></td>"
                f"<td>{_badge(r['grade'])}</td>"
                f"<td>{r.get('note','')}</td></tr>\n"
            )

    return f"""
<h2>Zone security settings</h2>
<table>
  <thead><tr>
    <th>Domain</th><th>Check</th><th>Recommended</th>
    <th>Actual</th><th>Grade</th><th>Notes</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>"""


def _html_email_table(domains, email_results) -> str:
    if not email_results:
        return ""

    rows = ""
    for domain in domains:
        result = email_results.get(domain)
        if not result:
            continue

        mx_text = "None" if not result["mx"] else (
            "Null MX" if not result["has_mail"]
            else ", ".join(f"{m['priority']} {m['host']}" for m in result["mx"][:3])
        )
        spf   = result["spf"]
        dmarc = result["dmarc"]
        dkim_count = len(result["dkim"])

        rows += (
            f"<tr><td><code>{domain}</code></td>"
            f"<td><small>{mx_text}</small></td>"
            f"<td>{_badge(spf['grade'])} <small>{spf['reason']}</small></td>"
            f"<td>{_badge(dmarc['grade'])} <small>{dmarc['reason']}</small></td>"
            f"<td>{'✅ ' + str(dkim_count) + ' selector(s)' if dkim_count else '—'}</td></tr>\n"
        )

    return f"""
<h2>Email security (live DNS)</h2>
<table>
  <thead><tr>
    <th>Domain</th><th>MX</th><th>SPF</th><th>DMARC</th><th>DKIM</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>"""


def _html_blacklist_table(domains, blacklist_results) -> str:
    if not blacklist_results:
        return ""

    rows = ""
    for domain in domains:
        result = blacklist_results.get(domain)
        if not result:
            continue

        listings = result.get("listings", [])
        detail = ""
        if listings:
            detail = "<br>".join(
                f"<small>{l.get('ip','')} on {l.get('blacklist','')}</small>"
                for l in listings[:5]
            )

        rows += (
            f"<tr><td><code>{domain}</code></td>"
            f"<td>{_badge(result.get('grade', 'INFO'))} "
            f"<small>{result.get('reason', '')}</small></td>"
            f"<td>{detail or '—'}</td></tr>\n"
        )

    return f"""
<h2>Blacklist (DNSBL)</h2>
<table>
  <thead><tr>
    <th>Domain</th><th>Status</th><th>Listings</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>"""


def _html_rdns_table(domains, rdns_results) -> str:
    if not rdns_results:
        return ""

    rows = ""
    for domain in domains:
        result = rdns_results.get(domain)
        if not result:
            continue

        ptr_results = result.get("results", [])
        detail = ""
        if ptr_results:
            detail = "<br>".join(
                f"<small>{r.get('ip','')} → {r.get('ptr','—')} "
                f"{'✅' if r.get('fcrdns') else '❌'}</small>"
                for r in ptr_results[:5]
            )

        rows += (
            f"<tr><td><code>{domain}</code></td>"
            f"<td>{_badge(result.get('grade', 'INFO'))} "
            f"<small>{result.get('reason', '')}</small></td>"
            f"<td>{detail or '—'}</td></tr>\n"
        )

    return f"""
<h2>Reverse DNS (PTR)</h2>
<table>
  <thead><tr>
    <th>Domain</th><th>Status</th><th>Details</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>"""


def _html_dns_tables(domains, dns_results) -> str:
    if not dns_results:
        return ""

    sections = ["<h2>DNS inventory</h2>"]

    for domain in domains:
        summary = dns_results.get(domain)
        if not summary:
            continue

        type_pills = " ".join(
            f'<span class="badge badge-info">{t}: {c}</span>'
            for t, c in summary["by_type"].items()
        )

        rows = ""
        for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
            proxied = '<span class="badge badge-warning">proxied</span>' if r["proxied"] else ""
            rows += (
                f"<tr>"
                f"<td><code>{r['type']}</code></td>"
                f"<td><code>{r['name']}</code></td>"
                f"<td><code>{_truncate(r['content'], 70)}</code></td>"
                f"<td>{r['ttl']}</td>"
                f"<td>{proxied}</td>"
                f"</tr>\n"
            )

        sections.append(f"""
<div class="domain-section">
  <h3 style="margin:24px 0 8px;color:#334155"><code>{domain}</code>
    — {summary['total']} records</h3>
  <p style="margin-bottom:12px">{type_pills}</p>
  <table>
    <thead><tr><th>Type</th><th>Name</th><th>Content</th><th>TTL</th><th></th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>""")

    return "\n".join(sections)


def _html_footer() -> str:
    return f"""
<div class="footer">
  Generated by <a href="https://github.com/wblv-dev/cloudflare-reporting">cloudflare-reporting</a>
  &nbsp;·&nbsp; Read-only — no changes made to any zone.
</div>
</div>
</body>
</html>"""
