"""
reporter.py — Report writer. Produces Markdown, HTML, and CSV output.

Markdown: human-readable, Git-friendly, good for the repo sample.
HTML:     visual dashboard, self-contained single file.
CSV:      machine-readable compliance summary, one row per domain.
"""

import csv
import html
import json as _json
import os as _os
from datetime import datetime, timezone
from typing import Dict, List

from domain_audit.lib.remediation import get_tooltip, collect_remediations, TOOLTIPS, STANDARDS


# ── Grade helpers ─────────────────────────────────────────────────────────────

_GRADE_ORDER = {"FAIL": 0, "WARN": 1, "INFO": 2, "PASS": 3}

GRADE_SYMBOL = {
    "PASS": "✅ PASS",
    "WARN": "⚠️ WARN",
    "FAIL": "❌ FAIL",
    "INFO": "ℹ️ INFO",
}

# HTML badge classes
GRADE_CLASS = {
    "PASS": "badge-success",
    "WARN": "badge-warning",
    "FAIL": "badge-danger",
    "INFO": "badge-info",
}


# Em dash for use in f-string expressions (backslash escapes not allowed in Python 3.10 f-exprs)
_DASH = "\u2014"


def _worst(grades: List[str]) -> str:
    if not grades:
        return "INFO"
    return min(grades, key=lambda g: _GRADE_ORDER.get(g, 99))


def _sym(grade: str) -> str:
    return GRADE_SYMBOL.get(grade, grade)


def _truncate(s: str, n: int = 80) -> str:
    return s if len(s) <= n else s[:n - 3] + "..."


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _esc(s) -> str:
    """HTML-escape untrusted content to prevent XSS."""
    if s is None:
        return ""
    return html.escape(str(s))


def _badge(grade: str, text: str = None) -> str:
    cls = GRADE_CLASS.get(grade, "badge-info")
    label = text or grade
    return f'<span class="badge {cls}">{_esc(label)}</span>'


def _tip(label: str) -> str:
    """Wrap a label in a tooltip span if a tooltip exists."""
    tooltip = get_tooltip(label)
    if not tooltip:
        return _esc(label)
    return f'<span class="tip" data-tip="{_esc(tooltip)}">{_esc(label)}</span>'


# ══════════════════════════════════════════════════════════════════════════════
# MARKDOWN
# ══════════════════════════════════════════════════════════════════════════════

def write_markdown(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
    **kwargs,
) -> None:
    sections = [
        _md_header(domains),
        _md_executive_summary(
            domains, email_results, security_results, dns_results,
            registrar_results, dns_sec_results, blacklist_results, rdns_results,
        ),
    ]

    for domain in domains:
        if domain in registrar_results:
            sections.append(_md_registrar(domain, registrar_results[domain]))
        if domain in dns_sec_results:
            sections.append(_md_dns_security(domain, dns_sec_results[domain]))
        if domain in dns_results:
            sections.append(_md_dns(domain, dns_results[domain]))
        if domain in email_results:
            sections.append(_md_email(domain, email_results[domain]))
        if domain in blacklist_results:
            sections.append(_md_blacklist(domain, blacklist_results[domain]))
        if domain in rdns_results:
            sections.append(_md_rdns(domain, rdns_results[domain]))
        if email_std_results and domain in email_std_results:
            sections.append(_md_email_standards(domain, email_std_results[domain]))
        if domain in security_results:
            sections.append(_md_security(domain, security_results[domain]))

    sections.append(
        "\n---\n\n"
        "*Generated by [domain-security-toolkit](https://github.com/wblv-dev/domain-security-toolkit). "
        "Read-only — no changes made to any zone.*\n"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sections))

    print(f"  Markdown report → {output_path}")


def _md_header(domains: List[str]) -> str:
    domain_list = ", ".join(f"`{d}`" for d in domains)
    return (
        f"# Domain Security Audit Report\n\n"
        f"**Generated:** {_ts()}  \n"
        f"**Domains:** {domain_list}  \n"
        f"**Tool:** [domain-security-toolkit](https://github.com/wblv-dev/domain-security-toolkit)\n\n"
        f"> Live DNS validation and security audit. "
        f"Grades reflect published state at time of generation.\n\n---\n"
    )


def _md_executive_summary(
    domains, email_results, security_results, dns_results,
    registrar_results, dns_sec_results, blacklist_results, rdns_results,
) -> str:
    lines = [
        "## Executive summary\n",
        "| Domain | DNS | Email | Zone | Registrar | DNSSEC | CAA | Blacklist | rDNS |",
        "|--------|-----|-------|------|-----------|--------|-----|-----------|------|",
    ]

    for d in domains:
        dns_count = dns_results.get(d, {}).get("total", "?")

        email = email_results.get(d, {})
        email_grade = _worst([
            email.get("spf", {}).get("grade", "INFO"),
            email.get("dmarc", {}).get("grade", "INFO"),
        ])

        sec = security_results.get(d)
        if sec:
            passed, total = sec["score"]
            sec_cell = f"{_sym(_worst([r['grade'] for r in sec['results']]))} ({passed}/{total})"
        else:
            sec_cell = "—"

        reg = registrar_results.get(d, {})
        reg_grade = _worst([
            reg.get("expiry", {}).get("grade", "INFO"),
            reg.get("lock", {}).get("grade", "INFO"),
        ])

        ds = dns_sec_results.get(d, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "?")
        caa_g = ds.get("caa", {}).get("grade", "?")

        bl_g = blacklist_results.get(d, {}).get("grade", "?")
        rdns_g = rdns_results.get(d, {}).get("grade", "?")

        lines.append(
            f"| `{d}` | {dns_count} | {_sym(email_grade)} | {sec_cell} "
            f"| {_sym(reg_grade)} | {_sym(dnssec_g)} | {_sym(caa_g)} "
            f"| {_sym(bl_g)} | {_sym(rdns_g)} |"
        )

    return "\n".join(lines) + "\n\n---\n"


def _md_registrar(domain: str, result: dict) -> str:
    lines = [f"## Registrar — `{domain}`\n"]

    if result.get("registrar"):
        lines.append(f"**Registrar:** {result['registrar']}\n")

    if result.get("nameservers"):
        lines.append(f"**Nameservers:** {', '.join(f'`{ns}`' for ns in result['nameservers'])}\n")

    exp = result.get("expiry", {})
    lines.append(f"**Expiry:** {_sym(exp.get('grade', 'INFO'))} — {exp.get('reason', 'Unknown')}")
    if exp.get("expiry"):
        lines.append(f"  \n**Expiry date:** `{exp['expiry']}`")

    lock = result.get("lock", {})
    lines.append(f"\n**Transfer lock:** {_sym(lock.get('grade', 'INFO'))} — {lock.get('reason', 'Unknown')}")

    return "\n".join(lines) + "\n\n"


def _md_dns_security(domain: str, result: dict) -> str:
    lines = [f"## DNS security — `{domain}`\n"]

    dnssec = result.get("dnssec", {})
    lines.append(f"**DNSSEC:** {_sym(dnssec.get('grade', 'INFO'))} — {dnssec.get('reason', '')}")

    caa = result.get("caa", {})
    lines.append(f"\n**CAA:** {_sym(caa.get('grade', 'INFO'))} — {caa.get('reason', '')}")

    if caa.get("records"):
        lines += ["\n| Flags | Tag | Value |", "|-------|-----|-------|"]
        for r in caa["records"]:
            lines.append(f"| {r.get('flags', '')} | `{r.get('tag', '')}` | `{r.get('value', '')}` |")

    dangling = result.get("dangling", {})
    lines.append(f"\n**Dangling CNAMEs:** {_sym(dangling.get('grade', 'INFO'))} — {dangling.get('reason', '')}")

    if dangling.get("dangling"):
        lines += ["\n| Record | Target |", "|--------|--------|"]
        for d in dangling["dangling"]:
            lines.append(f"| `{d['name']}` | `{d['target']}` |")

    return "\n".join(lines) + "\n\n"


def _md_blacklist(domain: str, result: dict) -> str:
    lines = [
        f"## Blacklist — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    listings = result.get("listings", [])
    if listings:
        lines += ["\n| IP | Blacklist | Reason |", "|-----|-----------|--------|"]
        for l in listings:
            lines.append(f"| `{l.get('ip', '')}` | {l.get('blacklist', '')} | {l.get('reason', '')} |")

    return "\n".join(lines) + "\n\n"


def _md_rdns(domain: str, result: dict) -> str:
    lines = [
        f"## Reverse DNS — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    ptr_results = result.get("results", [])
    if ptr_results:
        lines += ["\n| MX Host | IP | PTR | FCrDNS |", "|---------|-----|-----|--------|"]
        for r in ptr_results:
            fcrdns = "✅" if r.get("fcrdns") else "❌"
            ptr = r.get("ptr") or "—"
            lines.append(
                f"| `{r.get('mx_host', '')}` | `{r.get('ip', '')}` | `{ptr}` | {fcrdns} |"
            )

    return "\n".join(lines) + "\n\n"


def _md_email_standards(domain: str, result: dict) -> str:
    lines = [f"## Email standards — `{domain}`\n"]

    mta = result.get("mta_sts", {})
    lines.append(f"**MTA-STS:** {_sym(mta.get('grade', 'INFO'))} — {mta.get('reason', '')}")
    if mta.get("mode"):
        lines.append(f"  \n**Mode:** `{mta['mode']}`")

    tls = result.get("tlsrpt", {})
    lines.append(f"\n**TLSRPT:** {_sym(tls.get('grade', 'INFO'))} — {tls.get('reason', '')}")
    if tls.get("rua"):
        lines.append(f"  \n**Reporting:** `{tls['rua']}`")

    bimi = result.get("bimi", {})
    lines.append(f"\n**BIMI:** {_sym(bimi.get('grade', 'INFO'))} — {bimi.get('reason', '')}")

    return "\n".join(lines) + "\n\n"


def _md_dns(domain: str, summary: dict) -> str:
    proxied_note = f"  (**{summary['proxied']}** proxied)" if summary['proxied'] else ""
    lines = [f"## DNS inventory — `{domain}`\n",
             f"**Total:** {summary['total']} records{proxied_note}\n",
             "**By type:**\n",
             "| Type | Count |", "|------|-------|"]
    for rtype, count in summary["by_type"].items():
        lines.append(f"| `{rtype}` | {count} |")

    lines += ["\n**All records:**\n",
              "| Type | Name | Content | TTL | Proxied |",
              "|------|------|---------|-----|---------|"]
    for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
        proxied = "🟠 Yes" if r["proxied"] else "No"
        lines.append(
            f"| `{r['type']}` | `{r['name']}` "
            f"| `{_truncate(r['content'], 60)}` | {r['ttl']} | {proxied} |"
        )
    return "\n".join(lines) + "\n\n"


def _md_email(domain: str, result: dict) -> str:
    lines = [f"## Email security — `{domain}`\n"]

    if not result["has_mail"]:
        lines.append("**MX:** " + (
            "None — domain does not handle email.\n"
            if not result["mx"]
            else "Null MX (RFC 7505) — domain explicitly declares no mail.\n"
        ))
    else:
        lines += ["**MX records:**\n", "| Priority | Host |", "|----------|------|"]
        for mx in result["mx"]:
            lines.append(f"| {mx['priority']} | `{mx['host']}` |")
        lines.append("")

    spf   = result["spf"]
    dmarc = result["dmarc"]

    lines.append(f"**SPF:** {_sym(spf['grade'])} — {spf['reason']}")
    if spf.get("record"):
        lines.append(f"\n```\n{spf['record']}\n```\n")

    lines.append(f"**DMARC:** {_sym(dmarc['grade'])} — {dmarc['reason']}")
    if dmarc.get("rua"):
        lines.append(f"  \n**Reporting (rua):** `{dmarc['rua']}`")
    if dmarc.get("record"):
        lines.append(f"\n```\n{dmarc['record']}\n```\n")

    if result["dkim"]:
        lines += ["**DKIM selectors found:**\n",
                  "| Selector | Record (truncated) |",
                  "|----------|--------------------|"]
        for dk in result["dkim"]:
            lines.append(f"| `{dk['selector']}` | `{_truncate(dk['record'], 60)}` |")
    else:
        lines.append(
            "**DKIM:** No common selectors found. "
            "Add your provider's selector to `DKIM_SELECTORS` in `domain_audit/checks/email_security.py`.\n"
        )

    return "\n".join(lines) + "\n"


def _md_security(domain: str, result: dict) -> str:
    passed, total = result["score"]
    lines = [f"## Zone security — `{domain}`\n",
             f"**Score:** {passed}/{total} checks passed\n",
             "| Check | Recommended | Actual | Grade | Notes |",
             "|-------|-------------|--------|-------|-------|"]
    for r in result["results"]:
        lines.append(
            f"| {r['label']} | `{r.get('recommended','—')}` "
            f"| `{r.get('actual','—')}` | {_sym(r['grade'])} | {r.get('note','')} |"
        )

    failures = [r for r in result["results"] if r["grade"] in ("FAIL", "WARN")]
    if failures:
        lines.append("\n**Findings:**\n")
        for r in failures:
            if r.get("explanation"):
                lines.append(f"- **{r['label']}** ({_sym(r['grade'])}): {r['explanation']}")

    return "\n".join(lines) + "\n\n"


# ══════════════════════════════════════════════════════════════════════════════
# CSV
# ══════════════════════════════════════════════════════════════════════════════

def write_csv(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
    **kwargs,
) -> None:
    """Write a CSV compliance summary — one row per domain."""
    fieldnames = [
        "Domain", "DNS Records",
        "SPF", "DMARC", "DKIM Selectors",
        "Zone Security", "Zone Pass", "Zone Total",
        "Registrar", "Expiry", "Expiry Days", "Transfer Lock",
        "DNSSEC", "CAA", "Dangling CNAMEs",
        "Blacklist", "Reverse DNS",
        "MTA-STS", "TLSRPT", "BIMI",
    ]

    _estd = email_std_results or {}
    rows = []
    for d in domains:
        dns = dns_results.get(d, {})
        email = email_results.get(d, {})
        sec = security_results.get(d, {})
        reg = registrar_results.get(d, {})
        ds = dns_sec_results.get(d, {})
        bl = blacklist_results.get(d, {})
        rdns = rdns_results.get(d, {})
        es = _estd.get(d, {})

        passed, total = sec.get("score", (0, 0))

        rows.append({
            "Domain":          d,
            "DNS Records":     dns.get("total", 0),
            "SPF":             email.get("spf", {}).get("grade", ""),
            "DMARC":           email.get("dmarc", {}).get("grade", ""),
            "DKIM Selectors":  len(email.get("dkim", [])),
            "Zone Security":   _worst([r["grade"] for r in sec.get("results", [])]) if sec.get("results") else "",
            "Zone Pass":       passed,
            "Zone Total":      total,
            "Registrar":       reg.get("registrar", ""),
            "Expiry":          reg.get("expiry", {}).get("grade", ""),
            "Expiry Days":     reg.get("expiry", {}).get("days_remaining", ""),
            "Transfer Lock":   reg.get("lock", {}).get("grade", ""),
            "DNSSEC":          ds.get("dnssec", {}).get("grade", ""),
            "CAA":             ds.get("caa", {}).get("grade", ""),
            "Dangling CNAMEs": len(ds.get("dangling", {}).get("dangling", [])),
            "Blacklist":       bl.get("grade", ""),
            "Reverse DNS":     rdns.get("grade", ""),
            "MTA-STS":         es.get("mta_sts", {}).get("grade", ""),
            "TLSRPT":          es.get("tlsrpt", {}).get("grade", ""),
            "BIMI":            es.get("bimi", {}).get("grade", ""),
        })

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"  CSV report      → {output_path}")



# ══════════════════════════════════════════════════════════════════════════════
# HTML — template-based, data injected as JSON

def _read_chartjs() -> str:
    p = _os.path.join("/tmp", "chartjs.min.js")
    try:
        with open(p, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "/* Chart.js not found — run: curl -o /tmp/chartjs.min.js https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js */"


def _load_template() -> str:
    d = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
    with open(_os.path.join(d, "template.html"), "r", encoding="utf-8") as f:
        return f.read()


def _all_checks_list(domains, security_results, email_results, dns_sec_results,
                     registrar_results, blacklist_results, rdns_results, email_std_results):
    checks = []
    for d in domains:
        sec = security_results.get(d, {})
        for r in sec.get("results", []):
            checks.append({"domain": d, "category": "Zone Security", "check": r.get("label", ""),
                           "recommended": r.get("recommended", ""), "actual": r.get("actual", ""), "grade": r.get("grade", "INFO")})
        email = email_results.get(d, {})
        for key, label in [("spf", "SPF"), ("dmarc", "DMARC")]:
            e = email.get(key, {})
            checks.append({"domain": d, "category": "Email", "check": label, "recommended": "",
                           "actual": e.get("reason", ""), "grade": e.get("grade", "INFO")})
        ds = dns_sec_results.get(d, {})
        for key, label in [("dnssec", "DNSSEC"), ("caa", "CAA"), ("dangling", "Dangling CNAMEs")]:
            c = ds.get(key, {})
            checks.append({"domain": d, "category": "DNS Security", "check": label, "recommended": "",
                           "actual": c.get("reason", ""), "grade": c.get("grade", "INFO")})
        reg = registrar_results.get(d, {})
        for key, label in [("expiry", "Domain expiry"), ("lock", "Transfer lock")]:
            c = reg.get(key, {})
            checks.append({"domain": d, "category": "Infrastructure", "check": label, "recommended": "",
                           "actual": c.get("reason", ""), "grade": c.get("grade", "INFO")})
        bl = blacklist_results.get(d, {})
        checks.append({"domain": d, "category": "Infrastructure", "check": "Blacklist (DNSBL)", "recommended": "",
                       "actual": bl.get("reason", ""), "grade": bl.get("grade", "INFO")})
        rd = rdns_results.get(d, {})
        checks.append({"domain": d, "category": "Infrastructure", "check": "Reverse DNS", "recommended": "",
                       "actual": rd.get("reason", ""), "grade": rd.get("grade", "INFO")})
        es = (email_std_results or {}).get(d, {})
        for key, label in [("mta_sts", "MTA-STS"), ("tlsrpt", "TLSRPT"), ("bimi", "BIMI")]:
            c = es.get(key, {})
            checks.append({"domain": d, "category": "Email", "check": label, "recommended": "",
                           "actual": c.get("reason", ""), "grade": c.get("grade", "INFO")})
    return checks


def _domain_data(domains, dns_results, security_results, email_results,
                 dns_sec_results, registrar_results, blacklist_results,
                 rdns_results, email_std_results, all_checks):
    result = []
    for d in domains:
        dchecks = [c for c in all_checks if c["domain"] == d]
        grades = [c["grade"] for c in dchecks]
        p = sum(1 for g in grades if g == "PASS")
        w = sum(1 for g in grades if g == "WARN")
        f = sum(1 for g in grades if g == "FAIL")
        email = email_results.get(d, {})
        ds = dns_sec_results.get(d, {})
        sec = security_results.get(d, {})
        passed, total = sec.get("score", (0, 0))
        badges = [
            {"label": "Zone", "grade": f"{passed}/{total}" if total else "?"},
            {"label": "SPF", "grade": email.get("spf", {}).get("grade", "?")},
            {"label": "DMARC", "grade": email.get("dmarc", {}).get("grade", "?")},
            {"label": "DNSSEC", "grade": ds.get("dnssec", {}).get("grade", "?")},
        ]
        dns = dns_results.get(d, {})
        records = []
        for r in sorted(dns.get("records", []), key=lambda x: (x.get("type", ""), x.get("name", ""))):
            records.append({"type": r.get("type", ""), "name": r.get("name", ""),
                           "content": r.get("content", "")[:80], "ttl": r.get("ttl", "")})
        result.append({"domain": d, "pass": p, "warn": w, "fail": f,
                       "badges": badges, "checks": dchecks, "dnsRecords": records})
    return result


def _category_data(all_checks):
    cats = {}
    for c in all_checks:
        cat = c["category"]
        if cat not in cats:
            cats[cat] = {"name": cat, "pass": 0, "warn": 0, "fail": 0}
        g = c["grade"]
        if g == "PASS": cats[cat]["pass"] += 1
        elif g == "WARN": cats[cat]["warn"] += 1
        elif g == "FAIL": cats[cat]["fail"] += 1
    return list(cats.values())


def write_html(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    web_sec_results: Dict[str, dict] = None,
    ct_results: Dict[str, dict] = None,
    internetdb_results: Dict[str, dict] = None,
    obs_results: Dict[str, dict] = None,
    osint_results: Dict[str, dict] = None,
    output_path: str = "",
    diff_result: dict = None,
) -> None:
    template = _load_template()
    chartjs = _read_chartjs()

    all_checks = _all_checks_list(
        domains, security_results, email_results, dns_sec_results,
        registrar_results, blacklist_results, rdns_results, email_std_results,
    )

    # Add web security header checks to the all_checks list
    _ws = web_sec_results or {}
    for d in domains:
        ws = _ws.get(d, {})
        for h in ws.get("headers", []):
            all_checks.append({
                "domain": d, "category": "Web Security",
                "check": h.get("label", ""), "recommended": h.get("recommended", ""),
                "actual": h.get("actual", ""), "grade": h.get("grade", "INFO"),
            })
        sec_txt = ws.get("security_txt", {})
        if sec_txt:
            all_checks.append({
                "domain": d, "category": "Web Security",
                "check": "security.txt", "recommended": "Published (RFC 9116)",
                "actual": sec_txt.get("reason", ""), "grade": sec_txt.get("grade", "INFO"),
            })

    # Add Shodan InternetDB checks
    _idb = internetdb_results or {}
    for d in domains:
        idb = _idb.get(d, {})
        if idb.get("grade"):
            all_checks.append({
                "domain": d, "category": "Infrastructure",
                "check": "Open Ports (Shodan)", "recommended": "No risky ports exposed",
                "actual": idb.get("reason", ""), "grade": idb.get("grade", "INFO"),
            })

    # Add Mozilla Observatory checks
    _obs = obs_results or {}
    for d in domains:
        ob = _obs.get(d, {})
        if ob.get("grade"):
            all_checks.append({
                "domain": d, "category": "Web Security",
                "check": "Mozilla Observatory", "recommended": "Grade A or above",
                "actual": ob.get("reason", ""), "grade": ob.get("grade", "INFO"),
            })

    grades = {
        "pass": sum(1 for c in all_checks if c["grade"] == "PASS"),
        "warn": sum(1 for c in all_checks if c["grade"] == "WARN"),
        "fail": sum(1 for c in all_checks if c["grade"] == "FAIL"),
        "info": sum(1 for c in all_checks if c["grade"] == "INFO"),
    }
    total_records = sum(dns_results.get(d, {}).get("total", 0) for d in domains)

    domain_data = _domain_data(
        domains, dns_results, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results,
        rdns_results, email_std_results, all_checks,
    )
    findings = collect_remediations(
        domains, security_results, email_results, dns_sec_results,
        registrar_results, blacklist_results, rdns_results,
    )

    # Build CT data for domains
    _ct = ct_results or {}
    ct_data = []
    for d in domains:
        ct = _ct.get(d, {})
        if ct.get("total_certs", 0) > 0:
            ct_data.append({
                "domain": d,
                "total_certs": ct.get("total_certs", 0),
                "subdomains": ct.get("unique_subdomains", [])[:50],
                "issuers": ct.get("issuers", {}),
                "recent_certs": ct.get("recent_certs", [])[:10],
                "grade": ct.get("grade", "INFO"),
                "reason": ct.get("reason", ""),
            })

    # Build web security summary for domains
    web_data = []
    for d in domains:
        ws = _ws.get(d, {})
        if ws.get("headers"):
            tech = ws.get("tech", [])
            web_data.append({
                "domain": d,
                "headers": ws["headers"],
                "security_txt": ws.get("security_txt", {}),
                "tech": tech,
                "score": ws.get("score", (0, 0)),
            })

    audit_data = {
        "generated": _ts(),
        "domains": domains,
        "totalRecords": total_records,
        "grades": grades,
        "allChecks": all_checks,
        "domainData": domain_data,
        "categories": _category_data(all_checks),
        "findings": findings,
        "tooltips": TOOLTIPS,
        "standards": STANDARDS,
        "diff": diff_result,
        "ct": ct_data,
        "webSecurity": web_data,
        "internetdb": {d: _idb.get(d, {}) for d in domains if _idb.get(d)},
        "observatory": {d: _obs.get(d, {}) for d in domains if _obs.get(d)},
        "osint": osint_results or {},
    }

    # Escape data for safe embedding inside <script> tag — prevents XSS via </script> injection
    json_str = _json.dumps(audit_data, default=str)
    json_str = json_str.replace("<", "\\u003c").replace(">", "\\u003e")

    html = template.replace("/*CHARTJS_PLACEHOLDER*/", chartjs)
    html = html.replace("/*AUDIT_DATA*/null", json_str)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"  HTML report     \u2192 {output_path}")
