"""
reporter.py — Report writer. Produces Markdown, HTML, and CSV output.

Markdown: human-readable, Git-friendly, good for the repo sample.
HTML:     visual dashboard, self-contained single file.
CSV:      machine-readable compliance summary, one row per domain.
"""

import csv
import html
from datetime import datetime, timezone
from typing import Dict, List

from lib.remediation import get_tooltip, collect_remediations, TOOLTIPS


# ── Grade helpers ─────────────────────────────────────────────────────────────

_GRADE_ORDER = {"FAIL": 0, "WARN": 1, "INFO": 2, "PASS": 3}

GRADE_SYMBOL = {
    "PASS": "✅ PASS",
    "WARN": "⚠️ WARN",
    "FAIL": "❌ FAIL",
    "INFO": "ℹ️ INFO",
}

# HTML badge classes
GRADE_CLASS = {
    "PASS": "badge-success",
    "WARN": "badge-warning",
    "FAIL": "badge-danger",
    "INFO": "badge-info",
}


# Em dash for use in f-string expressions (backslash escapes not allowed in Python 3.10 f-exprs)
_DASH = "\u2014"


def _worst(grades: List[str]) -> str:
    if not grades:
        return "INFO"
    return min(grades, key=lambda g: _GRADE_ORDER.get(g, 99))


def _sym(grade: str) -> str:
    return GRADE_SYMBOL.get(grade, grade)


def _truncate(s: str, n: int = 80) -> str:
    return s if len(s) <= n else s[:n - 3] + "..."


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# ══════════════════════════════════════════════════════════════════════════════
# MARKDOWN
# ══════════════════════════════════════════════════════════════════════════════

def write_markdown(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    sections = [
        _md_header(domains),
        _md_executive_summary(
            domains, email_results, security_results, dns_results,
            registrar_results, dns_sec_results, blacklist_results, rdns_results,
        ),
    ]

    for domain in domains:
        if domain in registrar_results:
            sections.append(_md_registrar(domain, registrar_results[domain]))
        if domain in dns_sec_results:
            sections.append(_md_dns_security(domain, dns_sec_results[domain]))
        if domain in dns_results:
            sections.append(_md_dns(domain, dns_results[domain]))
        if domain in email_results:
            sections.append(_md_email(domain, email_results[domain]))
        if domain in blacklist_results:
            sections.append(_md_blacklist(domain, blacklist_results[domain]))
        if domain in rdns_results:
            sections.append(_md_rdns(domain, rdns_results[domain]))
        if email_std_results and domain in email_std_results:
            sections.append(_md_email_standards(domain, email_std_results[domain]))
        if domain in security_results:
            sections.append(_md_security(domain, security_results[domain]))

    sections.append(
        "\n---\n\n"
        "*Generated by [cloudflare-reporting](https://github.com/wblv-dev/cloudflare-reporting). "
        "Read-only — no changes made to any zone.*\n"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sections))

    print(f"  Markdown report → {output_path}")


def _md_header(domains: List[str]) -> str:
    domain_list = ", ".join(f"`{d}`" for d in domains)
    return (
        f"# Cloudflare DNS Audit Report\n\n"
        f"**Generated:** {_ts()}  \n"
        f"**Domains:** {domain_list}  \n"
        f"**Tool:** [cloudflare-reporting](https://github.com/wblv-dev/cloudflare-reporting)\n\n"
        f"> Live DNS validation and Cloudflare API audit. "
        f"Grades reflect published state at time of generation.\n\n---\n"
    )


def _md_executive_summary(
    domains, email_results, security_results, dns_results,
    registrar_results, dns_sec_results, blacklist_results, rdns_results,
) -> str:
    lines = [
        "## Executive summary\n",
        "| Domain | DNS | Email | Zone | Registrar | DNSSEC | CAA | Blacklist | rDNS |",
        "|--------|-----|-------|------|-----------|--------|-----|-----------|------|",
    ]

    for d in domains:
        dns_count = dns_results.get(d, {}).get("total", "?")

        email = email_results.get(d, {})
        email_grade = _worst([
            email.get("spf", {}).get("grade", "INFO"),
            email.get("dmarc", {}).get("grade", "INFO"),
        ])

        sec = security_results.get(d)
        if sec:
            passed, total = sec["score"]
            sec_cell = f"{_sym(_worst([r['grade'] for r in sec['results']]))} ({passed}/{total})"
        else:
            sec_cell = "—"

        reg = registrar_results.get(d, {})
        reg_grade = _worst([
            reg.get("expiry", {}).get("grade", "INFO"),
            reg.get("lock", {}).get("grade", "INFO"),
        ])

        ds = dns_sec_results.get(d, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "?")
        caa_g = ds.get("caa", {}).get("grade", "?")

        bl_g = blacklist_results.get(d, {}).get("grade", "?")
        rdns_g = rdns_results.get(d, {}).get("grade", "?")

        lines.append(
            f"| `{d}` | {dns_count} | {_sym(email_grade)} | {sec_cell} "
            f"| {_sym(reg_grade)} | {_sym(dnssec_g)} | {_sym(caa_g)} "
            f"| {_sym(bl_g)} | {_sym(rdns_g)} |"
        )

    return "\n".join(lines) + "\n\n---\n"


def _md_registrar(domain: str, result: dict) -> str:
    lines = [f"## Registrar — `{domain}`\n"]

    if result.get("registrar"):
        lines.append(f"**Registrar:** {result['registrar']}\n")

    if result.get("nameservers"):
        lines.append(f"**Nameservers:** {', '.join(f'`{ns}`' for ns in result['nameservers'])}\n")

    exp = result.get("expiry", {})
    lines.append(f"**Expiry:** {_sym(exp.get('grade', 'INFO'))} — {exp.get('reason', 'Unknown')}")
    if exp.get("expiry"):
        lines.append(f"  \n**Expiry date:** `{exp['expiry']}`")

    lock = result.get("lock", {})
    lines.append(f"\n**Transfer lock:** {_sym(lock.get('grade', 'INFO'))} — {lock.get('reason', 'Unknown')}")

    return "\n".join(lines) + "\n\n"


def _md_dns_security(domain: str, result: dict) -> str:
    lines = [f"## DNS security — `{domain}`\n"]

    dnssec = result.get("dnssec", {})
    lines.append(f"**DNSSEC:** {_sym(dnssec.get('grade', 'INFO'))} — {dnssec.get('reason', '')}")

    caa = result.get("caa", {})
    lines.append(f"\n**CAA:** {_sym(caa.get('grade', 'INFO'))} — {caa.get('reason', '')}")

    if caa.get("records"):
        lines += ["\n| Flags | Tag | Value |", "|-------|-----|-------|"]
        for r in caa["records"]:
            lines.append(f"| {r.get('flags', '')} | `{r.get('tag', '')}` | `{r.get('value', '')}` |")

    dangling = result.get("dangling", {})
    lines.append(f"\n**Dangling CNAMEs:** {_sym(dangling.get('grade', 'INFO'))} — {dangling.get('reason', '')}")

    if dangling.get("dangling"):
        lines += ["\n| Record | Target |", "|--------|--------|"]
        for d in dangling["dangling"]:
            lines.append(f"| `{d['name']}` | `{d['target']}` |")

    return "\n".join(lines) + "\n\n"


def _md_blacklist(domain: str, result: dict) -> str:
    lines = [
        f"## Blacklist — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    listings = result.get("listings", [])
    if listings:
        lines += ["\n| IP | Blacklist | Reason |", "|-----|-----------|--------|"]
        for l in listings:
            lines.append(f"| `{l.get('ip', '')}` | {l.get('blacklist', '')} | {l.get('reason', '')} |")

    return "\n".join(lines) + "\n\n"


def _md_rdns(domain: str, result: dict) -> str:
    lines = [
        f"## Reverse DNS — `{domain}`\n",
        f"**Status:** {_sym(result.get('grade', 'INFO'))} — {result.get('reason', '')}",
    ]

    ptr_results = result.get("results", [])
    if ptr_results:
        lines += ["\n| MX Host | IP | PTR | FCrDNS |", "|---------|-----|-----|--------|"]
        for r in ptr_results:
            fcrdns = "✅" if r.get("fcrdns") else "❌"
            ptr = r.get("ptr") or "—"
            lines.append(
                f"| `{r.get('mx_host', '')}` | `{r.get('ip', '')}` | `{ptr}` | {fcrdns} |"
            )

    return "\n".join(lines) + "\n\n"


def _md_email_standards(domain: str, result: dict) -> str:
    lines = [f"## Email standards — `{domain}`\n"]

    mta = result.get("mta_sts", {})
    lines.append(f"**MTA-STS:** {_sym(mta.get('grade', 'INFO'))} — {mta.get('reason', '')}")
    if mta.get("mode"):
        lines.append(f"  \n**Mode:** `{mta['mode']}`")

    tls = result.get("tlsrpt", {})
    lines.append(f"\n**TLSRPT:** {_sym(tls.get('grade', 'INFO'))} — {tls.get('reason', '')}")
    if tls.get("rua"):
        lines.append(f"  \n**Reporting:** `{tls['rua']}`")

    bimi = result.get("bimi", {})
    lines.append(f"\n**BIMI:** {_sym(bimi.get('grade', 'INFO'))} — {bimi.get('reason', '')}")

    return "\n".join(lines) + "\n\n"


def _md_dns(domain: str, summary: dict) -> str:
    lines = [f"## DNS inventory — `{domain}`\n",
             f"**Total:** {summary['total']} records  "
             f"(**{summary['proxied']}** proxied through Cloudflare)\n",
             "**By type:**\n",
             "| Type | Count |", "|------|-------|"]
    for rtype, count in summary["by_type"].items():
        lines.append(f"| `{rtype}` | {count} |")

    lines += ["\n**All records:**\n",
              "| Type | Name | Content | TTL | Proxied |",
              "|------|------|---------|-----|---------|"]
    for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
        proxied = "🟠 Yes" if r["proxied"] else "No"
        lines.append(
            f"| `{r['type']}` | `{r['name']}` "
            f"| `{_truncate(r['content'], 60)}` | {r['ttl']} | {proxied} |"
        )
    return "\n".join(lines) + "\n\n"


def _md_email(domain: str, result: dict) -> str:
    lines = [f"## Email security — `{domain}`\n"]

    if not result["has_mail"]:
        lines.append("**MX:** " + (
            "None — domain does not handle email.\n"
            if not result["mx"]
            else "Null MX (RFC 7505) — domain explicitly declares no mail.\n"
        ))
    else:
        lines += ["**MX records:**\n", "| Priority | Host |", "|----------|------|"]
        for mx in result["mx"]:
            lines.append(f"| {mx['priority']} | `{mx['host']}` |")
        lines.append("")

    spf   = result["spf"]
    dmarc = result["dmarc"]

    lines.append(f"**SPF:** {_sym(spf['grade'])} — {spf['reason']}")
    if spf.get("record"):
        lines.append(f"\n```\n{spf['record']}\n```\n")

    lines.append(f"**DMARC:** {_sym(dmarc['grade'])} — {dmarc['reason']}")
    if dmarc.get("rua"):
        lines.append(f"  \n**Reporting (rua):** `{dmarc['rua']}`")
    if dmarc.get("record"):
        lines.append(f"\n```\n{dmarc['record']}\n```\n")

    if result["dkim"]:
        lines += ["**DKIM selectors found:**\n",
                  "| Selector | Record (truncated) |",
                  "|----------|--------------------|"]
        for dk in result["dkim"]:
            lines.append(f"| `{dk['selector']}` | `{_truncate(dk['record'], 60)}` |")
    else:
        lines.append(
            "**DKIM:** No common selectors found. "
            "Add your provider's selector to `DKIM_SELECTORS` in `email_security.py`.\n"
        )

    return "\n".join(lines) + "\n"


def _md_security(domain: str, result: dict) -> str:
    passed, total = result["score"]
    lines = [f"## Zone security — `{domain}`\n",
             f"**Score:** {passed}/{total} checks passed\n",
             "| Check | Recommended | Actual | Grade | Notes |",
             "|-------|-------------|--------|-------|-------|"]
    for r in result["results"]:
        lines.append(
            f"| {r['label']} | `{r.get('recommended','—')}` "
            f"| `{r.get('actual','—')}` | {_sym(r['grade'])} | {r.get('note','')} |"
        )

    failures = [r for r in result["results"] if r["grade"] in ("FAIL", "WARN")]
    if failures:
        lines.append("\n**Findings:**\n")
        for r in failures:
            if r.get("explanation"):
                lines.append(f"- **{r['label']}** ({_sym(r['grade'])}): {r['explanation']}")

    return "\n".join(lines) + "\n\n"


# ══════════════════════════════════════════════════════════════════════════════
# CSV
# ══════════════════════════════════════════════════════════════════════════════

def write_csv(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    """Write a CSV compliance summary — one row per domain."""
    fieldnames = [
        "Domain", "DNS Records",
        "SPF", "DMARC", "DKIM Selectors",
        "Zone Security", "Zone Pass", "Zone Total",
        "Registrar", "Expiry", "Expiry Days", "Transfer Lock",
        "DNSSEC", "CAA", "Dangling CNAMEs",
        "Blacklist", "Reverse DNS",
        "MTA-STS", "TLSRPT", "BIMI",
    ]

    _estd = email_std_results or {}
    rows = []
    for d in domains:
        dns = dns_results.get(d, {})
        email = email_results.get(d, {})
        sec = security_results.get(d, {})
        reg = registrar_results.get(d, {})
        ds = dns_sec_results.get(d, {})
        bl = blacklist_results.get(d, {})
        rdns = rdns_results.get(d, {})
        es = _estd.get(d, {})

        passed, total = sec.get("score", (0, 0))

        rows.append({
            "Domain":          d,
            "DNS Records":     dns.get("total", 0),
            "SPF":             email.get("spf", {}).get("grade", ""),
            "DMARC":           email.get("dmarc", {}).get("grade", ""),
            "DKIM Selectors":  len(email.get("dkim", [])),
            "Zone Security":   _worst([r["grade"] for r in sec.get("results", [])]) if sec.get("results") else "",
            "Zone Pass":       passed,
            "Zone Total":      total,
            "Registrar":       reg.get("registrar", ""),
            "Expiry":          reg.get("expiry", {}).get("grade", ""),
            "Expiry Days":     reg.get("expiry", {}).get("days_remaining", ""),
            "Transfer Lock":   reg.get("lock", {}).get("grade", ""),
            "DNSSEC":          ds.get("dnssec", {}).get("grade", ""),
            "CAA":             ds.get("caa", {}).get("grade", ""),
            "Dangling CNAMEs": len(ds.get("dangling", {}).get("dangling", [])),
            "Blacklist":       bl.get("grade", ""),
            "Reverse DNS":     rdns.get("grade", ""),
            "MTA-STS":         es.get("mta_sts", {}).get("grade", ""),
            "TLSRPT":          es.get("tlsrpt", {}).get("grade", ""),
            "BIMI":            es.get("bimi", {}).get("grade", ""),
        })

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"  CSV report      → {output_path}")



# ══════════════════════════════════════════════════════════════════════════════
# HTML
# ══════════════════════════════════════════════════════════════════════════════

def write_html(
    domains: List[str],
    dns_results: Dict[str, dict],
    email_results: Dict[str, dict],
    security_results: Dict[str, dict],
    registrar_results: Dict[str, dict],
    dns_sec_results: Dict[str, dict],
    blacklist_results: Dict[str, dict],
    rdns_results: Dict[str, dict],
    email_std_results: Dict[str, dict] = None,
    output_path: str = "",
) -> None:
    _estd = email_std_results or {}

    # Collect remediations for the Remediations tab
    remediations = collect_remediations(
        domains, security_results, email_results,
        dns_sec_results, registrar_results, blacklist_results, rdns_results,
    )
    rem_count = len(remediations)

    out = "\n".join([
        _html_head(),
        _html_header(domains),
        '<div class="container">',
        _html_search_bar(),
        _html_tabs_nav(rem_count),
        # Tab: Summary
        '<div class="tab-panel active" id="tab-summary" role="tabpanel">',
        _html_summary_tab(
            domains, email_results, security_results, dns_results,
            registrar_results, dns_sec_results, blacklist_results, rdns_results,
        ),
        '</div>',
        # Tab: Security
        '<div class="tab-panel" id="tab-security" role="tabpanel">',
        _html_security_table(domains, security_results),
        '</div>',
        # Tab: Email
        '<div class="tab-panel" id="tab-email" role="tabpanel">',
        _html_email_table(domains, email_results),
        _html_email_standards_table(domains, _estd),
        '</div>',
        # Tab: DNS
        '<div class="tab-panel" id="tab-dns" role="tabpanel">',
        _html_dns_security_table(domains, dns_sec_results),
        _html_dns_tables(domains, dns_results),
        '</div>',
        # Tab: Remediations
        '<div class="tab-panel" id="tab-remediation" role="tabpanel">',
        _html_remediations_tab(remediations),
        '</div>',
        '</div>',  # close .container
        _html_footer(),
        _html_script(),
        '</body></html>',
    ])

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(out)

    print(f"  HTML report     \u2192 {output_path}")


def _esc(s) -> str:
    """HTML-escape untrusted content to prevent XSS."""
    if s is None:
        return ""
    return html.escape(str(s))


def _badge(grade: str, text: str = None) -> str:
    cls  = GRADE_CLASS.get(grade, "badge-info")
    label = text or grade
    return f'<span class="badge {cls}">{_esc(label)}</span>'


def _tip(label: str) -> str:
    """Wrap a label in a tooltip span if a tooltip exists for it."""
    tooltip_text = get_tooltip(label)
    if tooltip_text:
        return (
            f'<span class="has-tooltip" data-tooltip="{_esc(tooltip_text)}">'
            f'{_esc(label)}</span>'
        )
    return _esc(label)


# ── Summary tab ──────────────────────────────────────────────────────────────

def _html_summary_tab(
    domains, email_results, security_results, dns_results,
    registrar_results, dns_sec_results, blacklist_results, rdns_results,
) -> str:
    # Collect aggregate stats
    total_dns = 0
    total_fail = 0
    total_warn = 0
    for d in domains:
        total_dns += dns_results.get(d, {}).get("total", 0)
        sec = security_results.get(d)
        if sec:
            for r in sec.get("results", []):
                if r["grade"] == "FAIL":
                    total_fail += 1
                elif r["grade"] == "WARN":
                    total_warn += 1
        e = email_results.get(d, {})
        for key in ("spf", "dmarc"):
            g = e.get(key, {}).get("grade", "INFO")
            if g == "FAIL":
                total_fail += 1
            elif g == "WARN":
                total_warn += 1
        ds = dns_sec_results.get(d, {})
        for key in ("dnssec", "caa", "dangling"):
            g = ds.get(key, {}).get("grade", "INFO")
            if g == "FAIL":
                total_fail += 1
            elif g == "WARN":
                total_warn += 1
        reg = registrar_results.get(d, {})
        for key in ("expiry", "lock"):
            g = reg.get(key, {}).get("grade", "INFO")
            if g == "FAIL":
                total_fail += 1
            elif g == "WARN":
                total_warn += 1
        bl_g = blacklist_results.get(d, {}).get("grade", "INFO")
        if bl_g == "FAIL":
            total_fail += 1
        elif bl_g == "WARN":
            total_warn += 1
        rdns_g = rdns_results.get(d, {}).get("grade", "INFO")
        if rdns_g == "FAIL":
            total_fail += 1
        elif rdns_g == "WARN":
            total_warn += 1

    # Stats cards
    stats_html = f"""
<div class="stats-cards">
  <div class="stat-card c-navy"><h3>Domains Audited</h3><div class="val">{len(domains)}</div></div>
  <div class="stat-card c-blue"><h3>DNS Records</h3><div class="val">{total_dns}</div></div>
  <div class="stat-card c-red"><h3>Failures</h3><div class="val">{total_fail}</div></div>
  <div class="stat-card c-orange"><h3>Warnings</h3><div class="val">{total_warn}</div></div>
</div>"""

    # Per-domain summary table
    rows = ""
    for d in domains:
        email = email_results.get(d, {})
        spf_g = email.get("spf", {}).get("grade", "INFO")
        dmarc_g = email.get("dmarc", {}).get("grade", "INFO")

        sec = security_results.get(d)
        if sec:
            passed, total = sec["score"]
            sec_grade = _worst([r["grade"] for r in sec["results"]])
            zone_cell = f'{_badge(sec_grade, f"{passed}/{total}")}'
        else:
            zone_cell = _DASH

        ds = dns_sec_results.get(d, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "INFO")
        caa_g = ds.get("caa", {}).get("grade", "INFO")

        reg = registrar_results.get(d, {})
        reg_grade = _worst([
            reg.get("expiry", {}).get("grade", "INFO"),
            reg.get("lock", {}).get("grade", "INFO"),
        ])

        bl_g = blacklist_results.get(d, {}).get("grade", "INFO")
        rdns_g = rdns_results.get(d, {}).get("grade", "INFO")
        dns_count = dns_results.get(d, {}).get("total", 0)

        rows += (
            f'<tr data-domain="{_esc(d)}">'
            f'<td><code>{_esc(d)}</code></td>'
            f'<td>{dns_count}</td>'
            f'<td>{_badge(spf_g)}</td>'
            f'<td>{_badge(dmarc_g)}</td>'
            f'<td>{zone_cell}</td>'
            f'<td>{_badge(dnssec_g)}</td>'
            f'<td>{_badge(caa_g)}</td>'
            f'<td>{_badge(reg_grade)}</td>'
            f'<td>{_badge(bl_g)}</td>'
            f'<td>{_badge(rdns_g)}</td>'
            f'</tr>\n'
        )

    table_html = f"""
<h2 class="section-title">Per-Domain Overview</h2>
<table class="sortable">
  <thead><tr>
    <th>Domain <span class="sort-arrow"></span></th>
    <th>DNS <span class="sort-arrow"></span></th>
    <th>{_tip("SPF")} <span class="sort-arrow"></span></th>
    <th>{_tip("DMARC")} <span class="sort-arrow"></span></th>
    <th>Zone <span class="sort-arrow"></span></th>
    <th>{_tip("DNSSEC")} <span class="sort-arrow"></span></th>
    <th>{_tip("CAA")} <span class="sort-arrow"></span></th>
    <th>Registrar <span class="sort-arrow"></span></th>
    <th>{_tip("Blacklist (DNSBL)")} <span class="sort-arrow"></span></th>
    <th>{_tip("Reverse DNS")} <span class="sort-arrow"></span></th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>"""

    # Collapsible domain cards with infrastructure details
    cards_html = _html_summary_domain_cards(
        domains, email_results, security_results, dns_results,
        registrar_results, dns_sec_results, blacklist_results, rdns_results,
    )

    return stats_html + table_html + cards_html


def _html_summary_domain_cards(
    domains, email_results, security_results, dns_results,
    registrar_results, dns_sec_results, blacklist_results, rdns_results,
) -> str:
    """Collapsible per-domain cards with infrastructure details."""
    cards = []
    for domain in domains:
        badges_html = ""
        sec = security_results.get(domain)
        if sec:
            p, t = sec["score"]
            sec_grade = _worst([r["grade"] for r in sec["results"]])
            badges_html += f' {_badge(sec_grade, f"Zone {p}/{t}")}'
        email = email_results.get(domain, {})
        spf_g = email.get("spf", {}).get("grade", "INFO")
        dmarc_g = email.get("dmarc", {}).get("grade", "INFO")
        email_grade = _worst([spf_g, dmarc_g])
        badges_html += f' {_badge(email_grade, "Email")}'

        reg = registrar_results.get(domain, {})
        reg_grade = _worst([
            reg.get("expiry", {}).get("grade", "INFO"),
            reg.get("lock", {}).get("grade", "INFO"),
        ])
        badges_html += f' {_badge(reg_grade, "Registrar")}'

        ds = dns_sec_results.get(domain, {})
        dnssec_g = ds.get("dnssec", {}).get("grade", "INFO")
        badges_html += f' {_badge(dnssec_g, "DNSSEC")}'

        bl_g = blacklist_results.get(domain, {}).get("grade", "INFO")
        badges_html += f' {_badge(bl_g, "Blacklist")}'

        rdns_g = rdns_results.get(domain, {}).get("grade", "INFO")
        badges_html += f' {_badge(rdns_g, "rDNS")}'

        dns_count = dns_results.get(domain, {}).get("total", 0)

        body_parts = []

        # Registrar details
        if reg:
            exp = reg.get("expiry", {})
            lock = reg.get("lock", {})
            ns = ", ".join(_esc(n) for n in reg.get("nameservers", [])[:4]) or _DASH
            body_parts.append(
                f'<div style="margin-bottom:16px"><strong>Registrar &amp; Infrastructure</strong></div>'
                f'<table><thead><tr><th>Registrar</th>'
                f'<th>{_tip("Domain expiry")}</th>'
                f'<th>{_tip("Transfer lock")}</th>'
                f'<th>Nameservers</th></tr></thead>'
                f'<tbody><tr>'
                f'<td>{_esc(reg.get("registrar", _DASH))}</td>'
                f'<td>{_badge(exp.get("grade", "INFO"))} <small>{_esc(exp.get("reason", ""))}</small></td>'
                f'<td>{_badge(lock.get("grade", "INFO"))} '
                f'<small>{"Locked" if lock.get("locked") else "Unlocked"}</small></td>'
                f'<td><small>{ns}</small></td>'
                f'</tr></tbody></table>'
            )

        # Blacklist details
        bl = blacklist_results.get(domain, {})
        if bl:
            listings = bl.get("listings", [])
            detail = ""
            if listings:
                detail = ", ".join(
                    f'{_esc(l.get("ip", ""))} on {_esc(l.get("blacklist", ""))}'
                    for l in listings[:5]
                )
            body_parts.append(
                f'<div style="margin-top:12px"><strong>{_tip("Blacklist (DNSBL)")}</strong>: '
                f'{_badge(bl.get("grade", "INFO"))} '
                f'<small>{_esc(bl.get("reason", ""))}</small>'
                f'{" &mdash; " + detail if detail else ""}'
                f'</div>'
            )

        # rDNS details
        rdns = rdns_results.get(domain, {})
        if rdns:
            ptr_results = rdns.get("results", [])
            detail = ""
            if ptr_results:
                detail = ", ".join(
                    f'{_esc(r.get("ip", ""))} &rarr; {_esc(r.get("ptr", _DASH))}'
                    for r in ptr_results[:3]
                )
            body_parts.append(
                f'<div style="margin-top:8px"><strong>{_tip("Reverse DNS")}</strong>: '
                f'{_badge(rdns.get("grade", "INFO"))} '
                f'<small>{_esc(rdns.get("reason", ""))}</small>'
                f'{" &mdash; " + detail if detail else ""}'
                f'</div>'
            )

        body_html = "\n".join(body_parts)

        cards.append(
            f'<div class="domain-card" data-domain="{_esc(domain)}">'
            f'<div class="domain-card-header" onclick="toggleCard(this)">'
            f'<h3><code>{_esc(domain)}</code> <small style="color:var(--text-muted)">'
            f'({dns_count} records)</small></h3>'
            f'<div style="display:flex;align-items:center;gap:8px">'
            f'<span class="badges">{badges_html}</span>'
            f'<span class="domain-card-chevron" aria-hidden="true">&#9660;</span>'
            f'</div></div>'
            f'<div class="domain-card-body">{body_html}</div></div>'
        )

    if not cards:
        return ""
    return '<h2 class="section-title">Domain Details</h2>\n' + "\n".join(cards)


# ── Security tab ─────────────────────────────────────────────────────────────

def _html_security_table(domains, security_results) -> str:
    if not security_results:
        return '<div class="empty-state">No zone security data available.</div>'

    cards = []
    for domain in domains:
        sec = security_results.get(domain)
        if not sec:
            continue
        passed, total = sec["score"]
        overall = _worst([r["grade"] for r in sec["results"]])

        rows = ""
        for r in sec["results"]:
            rows += (
                f'<tr><td>{_tip(r["label"])}</td>'
                f'<td><code>{_esc(r.get("recommended", _DASH))}</code></td>'
                f'<td><code>{_esc(r.get("actual", _DASH))}</code></td>'
                f'<td>{_badge(r["grade"])}</td>'
                f'<td>{_esc(r.get("note", ""))}</td></tr>\n'
            )

        cards.append(
            f'<div class="domain-card" data-domain="{_esc(domain)}">'
            f'<div class="domain-card-header" onclick="toggleCard(this)">'
            f'<h3><code>{_esc(domain)}</code></h3>'
            f'<div style="display:flex;align-items:center;gap:8px">'
            f'{_badge(overall, f"{passed}/{total}")} '
            f'<span class="domain-card-chevron" aria-hidden="true">&#9660;</span>'
            f'</div></div>'
            f'<div class="domain-card-body">'
            f'<table class="sortable"><thead><tr>'
            f'<th>Check <span class="sort-arrow"></span></th>'
            f'<th>Recommended <span class="sort-arrow"></span></th>'
            f'<th>Actual <span class="sort-arrow"></span></th>'
            f'<th>Grade <span class="sort-arrow"></span></th>'
            f'<th>Notes <span class="sort-arrow"></span></th>'
            f'</tr></thead><tbody>{rows}</tbody></table>'
            f'</div></div>'
        )

    return f'<h2 class="section-title">Zone Security Settings</h2>\n' + "\n".join(cards)


# ── Email tab ────────────────────────────────────────────────────────────────

def _html_email_table(domains, email_results) -> str:
    if not email_results:
        return '<div class="empty-state">No email security data available.</div>'

    cards = []
    for domain in domains:
        result = email_results.get(domain)
        if not result:
            continue

        mx_text = "None" if not result["mx"] else (
            "Null MX" if not result["has_mail"]
            else ", ".join(f'{m["priority"]} {_esc(m["host"])}' for m in result["mx"][:3])
        )
        spf = result["spf"]
        dmarc = result["dmarc"]
        dkim_count = len(result["dkim"])
        email_grade = _worst([spf["grade"], dmarc["grade"]])

        spf_detail = ""
        if spf.get("record"):
            spf_detail = f'<div style="margin-top:8px"><code style="word-break:break-all;display:block;padding:8px">{_esc(spf["record"])}</code></div>'

        dmarc_detail = ""
        if dmarc.get("record"):
            dmarc_detail = f'<div style="margin-top:8px"><code style="word-break:break-all;display:block;padding:8px">{_esc(dmarc["record"])}</code></div>'
        if dmarc.get("rua"):
            dmarc_detail += f'<div style="margin-top:4px"><small>Reporting (rua): <code>{_esc(dmarc["rua"])}</code></small></div>'

        dkim_html = ""
        if result["dkim"]:
            dkim_rows = "".join(
                f'<tr><td><code>{_esc(dk["selector"])}</code></td>'
                f'<td><code>{_esc(_truncate(dk["record"], 60))}</code></td></tr>'
                for dk in result["dkim"]
            )
            dkim_html = (
                f'<div style="margin-top:12px"><strong>{_tip("DKIM")} Selectors</strong></div>'
                f'<table><thead><tr><th>Selector</th><th>Record</th></tr></thead>'
                f'<tbody>{dkim_rows}</tbody></table>'
            )

        mx_html = ""
        if result["has_mail"] and result["mx"]:
            mx_rows = "".join(
                f'<tr><td>{m["priority"]}</td><td><code>{_esc(m["host"])}</code></td></tr>'
                for m in result["mx"]
            )
            mx_html = (
                f'<div style="margin-top:12px"><strong>MX Records</strong></div>'
                f'<table><thead><tr><th>Priority</th><th>Host</th></tr></thead>'
                f'<tbody>{mx_rows}</tbody></table>'
            )

        cards.append(
            f'<div class="domain-card" data-domain="{_esc(domain)}">'
            f'<div class="domain-card-header" onclick="toggleCard(this)">'
            f'<h3><code>{_esc(domain)}</code></h3>'
            f'<div style="display:flex;align-items:center;gap:8px">'
            f'{_badge(email_grade)} '
            f'<small style="color:var(--text-muted)">{mx_text}</small>'
            f'<span class="domain-card-chevron" aria-hidden="true">&#9660;</span>'
            f'</div></div>'
            f'<div class="domain-card-body">'
            f'<table><thead><tr><th>Check</th><th>Grade</th><th>Details</th></tr></thead>'
            f'<tbody>'
            f'<tr><td>{_tip("SPF")}</td><td>{_badge(spf["grade"])}</td><td>{_esc(spf["reason"])}{spf_detail}</td></tr>'
            f'<tr><td>{_tip("DMARC")}</td><td>{_badge(dmarc["grade"])}</td><td>{_esc(dmarc["reason"])}{dmarc_detail}</td></tr>'
            f'<tr><td>{_tip("DKIM")}</td><td>{_badge("PASS" if dkim_count else "INFO")}</td>'
            f'<td>{dkim_count} selector(s) found</td></tr>'
            f'</tbody></table>'
            f'{mx_html}{dkim_html}'
            f'</div></div>'
        )

    return f'<h2 class="section-title">Email Security</h2>\n' + "\n".join(cards)


def _html_email_standards_table(domains, email_std_results) -> str:
    if not email_std_results:
        return ""

    rows = ""
    for domain in domains:
        result = email_std_results.get(domain)
        if not result:
            continue

        mta = result.get("mta_sts", {})
        tls = result.get("tlsrpt", {})
        bimi = result.get("bimi", {})

        rows += (
            f'<tr data-domain="{_esc(domain)}">'
            f"<td><code>{_esc(domain)}</code></td>"
            f"<td>{_badge(mta.get('grade', 'INFO'))} "
            f"<small>{_esc(mta.get('reason', ''))}</small></td>"
            f"<td>{_badge(tls.get('grade', 'INFO'))} "
            f"<small>{_esc(tls.get('reason', ''))}</small></td>"
            f"<td>{_badge(bimi.get('grade', 'INFO'))} "
            f"<small>{_esc(bimi.get('reason', ''))}</small></td></tr>\n"
        )

    return f"""
<h2 class="section-title">Email Standards ({_tip("MTA-STS")} / {_tip("TLSRPT")} / {_tip("BIMI")})</h2>
<table class="sortable">
  <thead><tr>
    <th>Domain <span class="sort-arrow"></span></th>
    <th>{_tip("MTA-STS")} <span class="sort-arrow"></span></th>
    <th>{_tip("TLSRPT")} <span class="sort-arrow"></span></th>
    <th>{_tip("BIMI")} <span class="sort-arrow"></span></th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>"""


# ── DNS tab ──────────────────────────────────────────────────────────────────

def _html_dns_security_table(domains, dns_sec_results) -> str:
    if not dns_sec_results:
        return '<div class="empty-state">No DNS security data available.</div>'

    cards = []
    for domain in domains:
        result = dns_sec_results.get(domain)
        if not result:
            continue

        dnssec = result.get("dnssec", {})
        caa = result.get("caa", {})
        dangling = result.get("dangling", {})
        dang_list = dangling.get("dangling", [])

        detail_rows = (
            f'<tr><td>{_tip("DNSSEC")}</td><td>{_badge(dnssec.get("grade", "INFO"))}</td>'
            f'<td>{_esc(dnssec.get("reason", ""))}</td></tr>'
            f'<tr><td>{_tip("CAA")}</td><td>{_badge(caa.get("grade", "INFO"))}</td>'
            f'<td>{_esc(caa.get("reason", ""))}</td></tr>'
            f'<tr><td>{_tip("Dangling CNAMEs")}</td><td>{_badge(dangling.get("grade", "INFO"))}</td>'
            f'<td>{len(dang_list)} dangling</td></tr>'
        )

        caa_records = caa.get("records", [])
        caa_html = ""
        if caa_records:
            caa_rows = "".join(
                f'<tr><td>{_esc(r.get("flags", ""))}</td><td><code>{_esc(r.get("tag", ""))}</code></td>'
                f'<td><code>{_esc(r.get("value", ""))}</code></td></tr>'
                for r in caa_records
            )
            caa_html = (
                f'<div style="margin-top:12px"><strong>CAA Records</strong></div>'
                f'<table><thead><tr><th>Flags</th><th>Tag</th><th>Value</th></tr></thead>'
                f'<tbody>{caa_rows}</tbody></table>'
            )

        dangling_html = ""
        if dang_list:
            dang_rows = "".join(
                f'<tr><td><code>{_esc(d["name"])}</code></td><td><code>{_esc(d["target"])}</code></td></tr>'
                for d in dang_list
            )
            dangling_html = (
                f'<div style="margin-top:12px"><strong>{_tip("Dangling CNAMEs")}</strong></div>'
                f'<table><thead><tr><th>Record</th><th>Target</th></tr></thead>'
                f'<tbody>{dang_rows}</tbody></table>'
            )

        overall = _worst([
            dnssec.get("grade", "INFO"),
            caa.get("grade", "INFO"),
            dangling.get("grade", "INFO"),
        ])

        cards.append(
            f'<div class="domain-card" data-domain="{_esc(domain)}">'
            f'<div class="domain-card-header" onclick="toggleCard(this)">'
            f'<h3><code>{_esc(domain)}</code></h3>'
            f'<div style="display:flex;align-items:center;gap:8px">'
            f'{_badge(overall)}'
            f'<span class="domain-card-chevron" aria-hidden="true">&#9660;</span>'
            f'</div></div>'
            f'<div class="domain-card-body">'
            f'<table><thead><tr><th>Check</th><th>Grade</th><th>Details</th></tr></thead>'
            f'<tbody>{detail_rows}</tbody></table>'
            f'{caa_html}{dangling_html}'
            f'</div></div>'
        )

    return f'<h2 class="section-title">DNS Security</h2>\n' + "\n".join(cards)


def _html_dns_tables(domains, dns_results) -> str:
    if not dns_results:
        return '<div class="empty-state">No DNS record data available.</div>'

    cards = []
    for domain in domains:
        summary = dns_results.get(domain)
        if not summary:
            continue

        type_pills = " ".join(
            f'<span class="badge badge-info">{_esc(t)}: {c}</span>'
            for t, c in summary["by_type"].items()
        )

        rows = ""
        for r in sorted(summary["records"], key=lambda x: (x["type"], x["name"])):
            proxied = '<span class="badge badge-warning">proxied</span>' if r["proxied"] else ""
            rows += (
                f"<tr>"
                f"<td><code>{_esc(r['type'])}</code></td>"
                f"<td><code>{_esc(r['name'])}</code></td>"
                f"<td><code>{_esc(_truncate(r['content'], 70))}</code></td>"
                f"<td>{r['ttl']}</td>"
                f"<td>{proxied}</td>"
                f"</tr>\n"
            )

        cards.append(
            f'<div class="domain-card" data-domain="{_esc(domain)}">'
            f'<div class="domain-card-header" onclick="toggleCard(this)">'
            f'<h3><code>{_esc(domain)}</code> <small style="color:var(--text-muted)">'
            f'&mdash; {summary["total"]} records</small></h3>'
            f'<div style="display:flex;align-items:center;gap:8px">'
            f'<span>{type_pills}</span>'
            f'<span class="domain-card-chevron" aria-hidden="true">&#9660;</span>'
            f'</div></div>'
            f'<div class="domain-card-body">'
            f'<table class="sortable"><thead><tr>'
            f'<th>Type <span class="sort-arrow"></span></th>'
            f'<th>Name <span class="sort-arrow"></span></th>'
            f'<th>Content <span class="sort-arrow"></span></th>'
            f'<th>TTL <span class="sort-arrow"></span></th>'
            f'<th> </th></tr></thead>'
            f'<tbody>{rows}</tbody></table>'
            f'</div></div>'
        )

    return f'<h2 class="section-title">DNS Inventory</h2>\n' + "\n".join(cards)


# ── Remediations tab ─────────────────────────────────────────────────────────

_PRIORITY_CLASS = {
    "Critical": "badge-danger",
    "High": "badge-warning",
    "Medium": "badge-info",
    "Low": "badge-info",
}

_PRIORITY_COLOR = {
    "Critical": "#dc2626",
    "High": "#d97706",
    "Medium": "#3b82f6",
    "Low": "#94a3b8",
}


def _html_remediations_tab(remediations: List[Dict]) -> str:
    if not remediations:
        return '<div class="empty-state">No remediations needed -- all checks passed.</div>'

    # Group by priority
    groups = {}
    for r in remediations:
        prio = r.get("priority", "Low")
        groups.setdefault(prio, []).append(r)

    sections = []
    idx = 0
    for prio in ["Critical", "High", "Medium", "Low"]:
        items = groups.get(prio, [])
        if not items:
            continue

        prio_cls = _PRIORITY_CLASS.get(prio, "badge-info")
        prio_color = _PRIORITY_COLOR.get(prio, "#94a3b8")

        cards_html = ""
        for finding in items:
            idx += 1
            grade_badge = _badge(finding["grade"])
            prio_badge = f'<span class="badge {prio_cls}">{_esc(prio)}</span>'

            # Step-by-step instructions
            steps = finding.get("steps", [])
            steps_html = ""
            if steps:
                step_items = "".join(
                    f'<li>{_esc(s)}</li>' for s in steps
                )
                steps_html = f'<ol class="rem-steps">{step_items}</ol>'

            actual = finding.get("actual", "")
            recommended = finding.get("recommended", "")
            actual_html = f'<div class="rem-actual"><strong>Current:</strong> <code>{_esc(actual)}</code></div>' if actual else ""
            rec_html = f'<div class="rem-rec"><strong>Recommended:</strong> <code>{_esc(recommended)}</code></div>' if recommended else ""

            cards_html += (
                f'<div class="rem-card domain-card" data-domain="{_esc(finding.get("domain", ""))}">'
                f'<div class="domain-card-header" onclick="toggleCard(this)">'
                f'<h3>{prio_badge} {grade_badge} '
                f'{_tip(finding.get("check", ""))} '
                f'<small style="color:var(--text-muted)">on <code>{_esc(finding.get("domain", ""))}</code></small></h3>'
                f'<span class="domain-card-chevron" aria-hidden="true">&#9660;</span>'
                f'</div>'
                f'<div class="domain-card-body">'
                f'<div class="rem-risk"><strong>Risk:</strong> {_esc(finding.get("risk", ""))}</div>'
                f'{actual_html}{rec_html}'
                f'{steps_html}'
                f'</div></div>'
            )

        sections.append(
            f'<div class="rem-priority-group">'
            f'<h3 style="color:{prio_color};margin:20px 0 12px;font-size:1.05em">'
            f'<span class="badge {prio_cls}">{_esc(prio)}</span> '
            f'{len(items)} finding{"s" if len(items) != 1 else ""}</h3>'
            f'{cards_html}'
            f'</div>'
        )

    count_by_prio = " &middot; ".join(
        f'{len(groups.get(p, []))} {p}'
        for p in ["Critical", "High", "Medium", "Low"]
        if groups.get(p)
    )

    return (
        f'<h2 class="section-title">Remediations</h2>'
        f'<div style="margin-bottom:16px;color:var(--text-muted);font-size:.9em">'
        f'{len(remediations)} findings requiring attention: {count_by_prio}</div>'
        + "\n".join(sections)
    )


# ── HTML scaffolding ─────────────────────────────────────────────────────────

def _html_footer() -> str:
    return """
<div class="footer">
  Generated by <a href="https://github.com/wblv-dev/cloudflare-reporting">cloudflare-reporting</a>
  &middot; Read-only &mdash; no changes made to any zone.
</div>"""


def _html_tabs_nav(rem_count: int = 0) -> str:
    tabs = [
        ("tab-summary", "Summary"),
        ("tab-security", "Security"),
        ("tab-email", "Email"),
        ("tab-dns", "DNS"),
        ("tab-remediation", f'Remediations <span class="tab-count-badge">{rem_count}</span>' if rem_count else "Remediations"),
    ]
    buttons = "\n".join(
        f'  <button class="tab-btn{" active" if i == 0 else ""}" '
        f'data-tab="{tid}" role="tab" aria-selected="{"true" if i == 0 else "false"}">'
        f'{label}</button>'
        for i, (tid, label) in enumerate(tabs)
    )
    return f'<nav class="tabs-nav" role="tablist">\n{buttons}\n</nav>'


def _html_head() -> str:
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Cloudflare DNS Audit Report</title>
<style>
/* ── Reset & Base ──────────────────────────────────────────── */
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}
:root{
  --bg:#f0f2f5;--bg-card:#fff;--text:#1a1a2e;--text-muted:#64748b;
  --border:#e2e8f0;--header-bg:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);
  --header-text:#fff;--th-bg:#0f3460;--th-text:#fff;--hover-row:#f8fafc;
  --code-bg:#f1f5f9;--shadow:0 1px 4px rgba(0,0,0,.1);
  --accent:#0f3460;--accent-light:#3b82f6;
  --transition-speed:.25s;
}
html[data-theme="dark"]{
  --bg:#0f172a;--bg-card:#1e293b;--text:#e2e8f0;--text-muted:#94a3b8;
  --border:#334155;--header-bg:linear-gradient(135deg,#0f172a 0%,#1e293b 60%,#1e3a5f 100%);
  --header-text:#e2e8f0;--th-bg:#1e3a5f;--th-text:#e2e8f0;--hover-row:#334155;
  --code-bg:#334155;--shadow:0 1px 4px rgba(0,0,0,.4);
  --accent:#60a5fa;--accent-light:#93c5fd;
}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
  line-height:1.6;color:var(--text);background:var(--bg);
  transition:background var(--transition-speed),color var(--transition-speed)}

/* ── Header ────────────────────────────────────────────────── */
.header{background:var(--header-bg);color:var(--header-text);padding:32px 20px}
.header-inner{max-width:1200px;margin:0 auto;display:flex;
  justify-content:space-between;align-items:center;flex-wrap:wrap;gap:16px}
.header h1{font-size:1.8em;font-weight:700}
.header .meta{opacity:.85;font-size:.9em}
.header-actions{display:flex;gap:10px;align-items:center}
.theme-toggle{background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.25);
  color:var(--header-text);padding:8px 14px;border-radius:8px;cursor:pointer;
  font-size:.85em;transition:background .2s}
.theme-toggle:hover{background:rgba(255,255,255,.25)}

/* ── Container ─────────────────────────────────────────────── */
.container{max-width:1200px;margin:0 auto;padding:24px 20px}

/* ── Search bar ────────────────────────────────────────────── */
.search-bar{margin-bottom:20px}
.search-bar input{width:100%;padding:12px 16px 12px 42px;border:2px solid var(--border);
  border-radius:10px;font-size:.95em;background:var(--bg-card);color:var(--text);
  transition:border-color .2s,box-shadow .2s;outline:none}
.search-bar input:focus{border-color:var(--accent-light);box-shadow:0 0 0 3px rgba(59,130,246,.15)}
.search-bar{position:relative}
.search-bar::before{content:"\\1F50D";position:absolute;left:14px;top:50%;
  transform:translateY(-50%);font-size:1em;opacity:.5;pointer-events:none}

/* ── Tabs ──────────────────────────────────────────────────── */
.tabs-nav{display:flex;gap:4px;border-bottom:2px solid var(--border);margin-bottom:24px;
  overflow-x:auto;-webkit-overflow-scrolling:touch}
.tab-btn{padding:10px 20px;border:none;background:transparent;color:var(--text-muted);
  font-size:.9em;font-weight:600;cursor:pointer;border-bottom:3px solid transparent;
  white-space:nowrap;transition:color .2s,border-color .2s,background .2s;
  border-radius:8px 8px 0 0}
.tab-btn:hover{color:var(--text);background:rgba(0,0,0,.03)}
.tab-btn.active{color:var(--accent);border-bottom-color:var(--accent)}
html[data-theme="dark"] .tab-btn:hover{background:rgba(255,255,255,.05)}
.tab-panel{display:none;animation:fadeIn .3s ease}
.tab-panel.active{display:block}
@keyframes fadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}

/* ── Tab count badge ──────────────────────────────────────── */
.tab-count-badge{display:inline-flex;align-items:center;justify-content:center;
  background:#dc2626;color:#fff;font-size:.7em;font-weight:700;min-width:20px;
  height:20px;border-radius:10px;padding:0 6px;margin-left:6px;vertical-align:middle}

/* ── Stats cards ──────────────────────────────────────────── */
.stats-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin:24px 0}
.stat-card{padding:24px;border-radius:12px;color:#fff;position:relative;overflow:hidden;
  transition:transform .2s,box-shadow .2s}
.stat-card:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,.15)}
.stat-card h3{font-size:.75em;text-transform:uppercase;letter-spacing:.8px;opacity:.9;margin-bottom:8px}
.stat-card .val{font-size:2.2em;font-weight:700}
.c-navy{background:linear-gradient(135deg,#1a1a2e,#0f3460)}
.c-green{background:linear-gradient(135deg,#065f46,#059669)}
.c-orange{background:linear-gradient(135deg,#92400e,#d97706)}
.c-red{background:linear-gradient(135deg,#7f1d1d,#dc2626)}
.c-blue{background:linear-gradient(135deg,#1e3a8a,#3b82f6)}

/* ── Domain cards (collapsible) ────────────────────────────── */
.domain-card{background:var(--bg-card);border:1px solid var(--border);border-radius:12px;
  margin-bottom:16px;overflow:hidden;transition:box-shadow .2s;box-shadow:var(--shadow)}
.domain-card:hover{box-shadow:0 4px 12px rgba(0,0,0,.1)}
.domain-card-header{padding:16px 20px;cursor:pointer;display:flex;
  justify-content:space-between;align-items:center;user-select:none;
  transition:background .2s}
.domain-card-header:hover{background:var(--hover-row)}
.domain-card-header h3{font-size:1em;font-weight:600;display:flex;align-items:center;gap:10px}
.domain-card-header .badges{display:flex;gap:6px;flex-wrap:wrap}
.domain-card-chevron{transition:transform .3s ease;font-size:.8em;color:var(--text-muted)}
.domain-card.open .domain-card-chevron{transform:rotate(180deg)}
.domain-card-body{max-height:0;overflow:hidden;transition:max-height .4s ease,padding .3s ease;
  padding:0 20px}
.domain-card.open .domain-card-body{max-height:3000px;padding:0 20px 20px}

/* ── Tables ────────────────────────────────────────────────── */
table{width:100%;border-collapse:collapse;margin:16px 0;border-radius:8px;
  overflow:hidden;box-shadow:var(--shadow);background:var(--bg-card)}
th{background:var(--th-bg);color:var(--th-text);padding:12px 16px;text-align:left;
  font-size:.8em;font-weight:600;text-transform:uppercase;letter-spacing:.3px;
  cursor:pointer;user-select:none;white-space:nowrap;transition:background .2s}
th:hover{background:#1e3a5f}
html[data-theme="dark"] th:hover{background:#2d4a6f}
th .sort-arrow{display:inline-block;margin-left:4px;opacity:.5;font-size:.7em}
th.sort-asc .sort-arrow::after{content:"\\25B2"}
th.sort-desc .sort-arrow::after{content:"\\25BC"}
td{padding:12px 16px;border-bottom:1px solid var(--border);font-size:.88em;vertical-align:top;
  transition:background .15s}
tr:last-child td{border-bottom:none}
tr:hover td{background:var(--hover-row)}

/* ── Badges ────────────────────────────────────────────────── */
.badge{display:inline-block;padding:3px 10px;border-radius:12px;
  font-size:.8em;font-weight:600;white-space:nowrap;transition:transform .15s}
.badge:hover{transform:scale(1.05)}
.badge-success{background:#d1fae5;color:#065f46}
.badge-warning{background:#fef3c7;color:#92400e}
.badge-danger{background:#fee2e2;color:#991b1b}
.badge-info{background:#dbeafe;color:#1e40af}
html[data-theme="dark"] .badge-success{background:#064e3b;color:#6ee7b7}
html[data-theme="dark"] .badge-warning{background:#78350f;color:#fcd34d}
html[data-theme="dark"] .badge-danger{background:#7f1d1d;color:#fca5a5}
html[data-theme="dark"] .badge-info{background:#1e3a8a;color:#93c5fd}

/* ── Tooltips ─────────────────────────────────────────────── */
.has-tooltip{position:relative;border-bottom:1px dotted var(--text-muted);cursor:help}
.has-tooltip::after{content:attr(data-tooltip);position:absolute;top:100%;margin-top:8px;
  left:0;background:#1e293b;color:#e2e8f0;padding:8px 12px;
  border-radius:8px;font-size:.78em;font-weight:400;white-space:normal;width:max-content;
  max-width:300px;line-height:1.4;box-shadow:0 4px 12px rgba(0,0,0,.3);z-index:1000;
  opacity:0;pointer-events:none;transition:opacity .2s .5s,transform .2s .5s;
  transform:translateY(-4px)}
.has-tooltip:hover::after{opacity:1;transform:translateY(0)}
html[data-theme="dark"] .has-tooltip::after{background:#334155;color:#f1f5f9}
.has-tooltip::before{content:"";position:absolute;top:100%;margin-top:-4px;left:12px;
  border:6px solid transparent;border-bottom-color:#1e293b;
  z-index:1001;opacity:0;pointer-events:none;transition:opacity .2s .5s}
.has-tooltip:hover::before{opacity:1}
html[data-theme="dark"] .has-tooltip::before{border-bottom-color:#334155}
td{position:relative}
th .has-tooltip{color:inherit;border-bottom-color:rgba(255,255,255,.4)}

/* ── Remediation cards ────────────────────────────────────── */
.rem-card .domain-card-body{font-size:.9em}
.rem-risk{margin-bottom:12px;padding:12px;background:rgba(220,38,38,.06);
  border-radius:8px;border-left:3px solid #dc2626;color:var(--text)}
html[data-theme="dark"] .rem-risk{background:rgba(220,38,38,.12)}
.rem-actual,.rem-rec{margin:6px 0;font-size:.9em}
.rem-steps{margin:12px 0 0 20px;line-height:1.8}
.rem-steps li{margin-bottom:4px}
.rem-priority-group{margin-bottom:12px}

/* ── Misc ──────────────────────────────────────────────────── */
code{font-family:'SF Mono',Monaco,Consolas,monospace;background:var(--code-bg);
  padding:1px 6px;border-radius:4px;font-size:.85em;transition:background .2s}
.section-title{font-size:1.3em;font-weight:600;color:var(--accent);margin:32px 0 16px;
  padding-bottom:8px;border-bottom:2px solid var(--border)}
.empty-state{text-align:center;padding:40px;color:var(--text-muted);font-size:.95em}
.footer{text-align:center;padding:32px;color:var(--text-muted);font-size:.85em;
  border-top:1px solid var(--border);margin-top:40px}
.footer a{color:var(--accent-light);text-decoration:none}
.footer a:hover{text-decoration:underline}

/* ── Responsive ────────────────────────────────────────────── */
@media(max-width:768px){
  .header h1{font-size:1.3em}
  .header-inner{flex-direction:column;align-items:flex-start}
  .stats-cards{grid-template-columns:1fr 1fr}
  .tabs-nav{gap:2px}
  .tab-btn{padding:8px 12px;font-size:.8em}
  td,th{padding:8px 10px;font-size:.8em}
  .domain-card-header{padding:12px 14px}
}
@media(max-width:480px){
  .stats-cards{grid-template-columns:1fr}
  .container{padding:16px 12px}
}
</style>
</head>
<body>"""


def _html_header(domains: List[str]) -> str:
    domain_list = ", ".join(f"<code>{_esc(d)}</code>" for d in domains)
    return f"""
<div class="header">
  <div class="header-inner">
    <div>
      <h1>Cloudflare DNS Audit Report</h1>
      <div class="meta">Domains: {domain_list}</div>
    </div>
    <div class="header-actions">
      <span class="meta">Generated: {_ts()}</span>
      <button class="theme-toggle" onclick="toggleTheme()" aria-label="Toggle dark mode"
        title="Toggle dark/light mode">&#9790; Dark mode</button>
    </div>
  </div>
</div>"""


def _html_search_bar() -> str:
    return """
<div class="search-bar">
  <input type="text" id="domain-search" placeholder="Filter domains..."
    aria-label="Filter domains by name" autocomplete="off">
</div>"""


def _html_script() -> str:
    return """
<script>
/* ── Theme toggle ──────────────────────────────────────────── */
function toggleTheme(){
  var html=document.documentElement;
  var btn=document.querySelector('.theme-toggle');
  if(html.getAttribute('data-theme')==='dark'){
    html.removeAttribute('data-theme');
    btn.innerHTML='&#9790; Dark mode';
    localStorage.setItem('cf-audit-theme','light');
  }else{
    html.setAttribute('data-theme','dark');
    btn.innerHTML='&#9788; Light mode';
    localStorage.setItem('cf-audit-theme','dark');
  }
}
(function(){
  var saved=localStorage.getItem('cf-audit-theme');
  if(saved==='dark'){
    document.documentElement.setAttribute('data-theme','dark');
    var btn=document.querySelector('.theme-toggle');
    if(btn) btn.innerHTML='&#9788; Light mode';
  }
})();

/* ── Tab switching ─────────────────────────────────────────── */
document.querySelectorAll('.tab-btn').forEach(function(btn){
  btn.addEventListener('click',function(){
    document.querySelectorAll('.tab-btn').forEach(function(b){
      b.classList.remove('active');
      b.setAttribute('aria-selected','false');
    });
    document.querySelectorAll('.tab-panel').forEach(function(p){
      p.classList.remove('active');
    });
    btn.classList.add('active');
    btn.setAttribute('aria-selected','true');
    var panel=document.getElementById(btn.getAttribute('data-tab'));
    if(panel) panel.classList.add('active');
  });
});

/* ── Collapsible cards ─────────────────────────────────────── */
function toggleCard(header){
  var card=header.parentElement;
  card.classList.toggle('open');
}

/* ── Search / filter ───────────────────────────────────────── */
var searchInput=document.getElementById('domain-search');
if(searchInput){
  searchInput.addEventListener('input',function(){
    var q=this.value.toLowerCase().trim();
    /* Filter domain cards */
    document.querySelectorAll('.domain-card').forEach(function(card){
      var domain=(card.getAttribute('data-domain')||'').toLowerCase();
      card.style.display=(!q||domain.indexOf(q)!==-1)?'':'none';
    });
    /* Filter table rows with data-domain */
    document.querySelectorAll('tr[data-domain]').forEach(function(row){
      var domain=(row.getAttribute('data-domain')||'').toLowerCase();
      row.style.display=(!q||domain.indexOf(q)!==-1)?'':'none';
    });
  });
}

/* ── Sortable tables ───────────────────────────────────────── */
document.querySelectorAll('table.sortable').forEach(function(table){
  var headers=table.querySelectorAll('th');
  headers.forEach(function(th,colIdx){
    th.addEventListener('click',function(){
      var tbody=table.querySelector('tbody');
      if(!tbody) return;
      var rows=Array.from(tbody.querySelectorAll('tr'));
      var isAsc=th.classList.contains('sort-asc');
      /* Clear all sort classes in this table */
      headers.forEach(function(h){h.classList.remove('sort-asc','sort-desc');});
      if(isAsc){
        th.classList.add('sort-desc');
      }else{
        th.classList.add('sort-asc');
      }
      var dir=th.classList.contains('sort-asc')?1:-1;
      rows.sort(function(a,b){
        var aText=(a.children[colIdx]?a.children[colIdx].textContent:'').trim().toLowerCase();
        var bText=(b.children[colIdx]?b.children[colIdx].textContent:'').trim().toLowerCase();
        var aNum=parseFloat(aText);
        var bNum=parseFloat(bText);
        if(!isNaN(aNum)&&!isNaN(bNum)) return (aNum-bNum)*dir;
        if(aText<bText) return -1*dir;
        if(aText>bText) return 1*dir;
        return 0;
      });
      rows.forEach(function(row){tbody.appendChild(row);});
    });
  });
});
</script>"""
